### ISSUE TITLE
Specs 1.1 and 1.2 lack a title for "Flow information" type

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-spec#1000]
**Link to problem area**: any request which may return user interactive auth flow information, e.g. [here](https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3register).

**Issue**: The description of a 401 response refers to a `Flow information` type. That type is described below, but without a `<caption>` making it hard to find.

![diagnosis](https://user-images.githubusercontent.com/8614563/159905006-899b1d0e-e796-4129-a625-a730675b6ac0.png)

Cause unclear, though I wonder if the space in `Flow information` is causing trouble.

**Comment by turt2live** [comment]
this would be the OpenAPI `title` missing for the type, I believe.

**Comment by DMRobertson** [comment]
AFAICS the `title` exists:

https://github.com/matrix-org/matrix-spec/blob/00c6a866e29c8694b9b8f1beaf9bc0bf8c513249/data/api/client-server/definitions/auth_response.yaml#L14-L35

**Comment by DMRobertson** [comment]
Adding `{{ printf "%#v" .title }}` just before this line, I see that `.title` is `<nil>` when generating the table for Flow information.

**Comment by DMRobertson** [comment]
Additional debugging: it looks like this call to `get-additional-objects` produces an additional object whose `enum` is nil.

https://github.com/matrix-org/matrix-spec/blob/942f865f64ba8353add123b3e80bf80ff6d83add/layouts/partials/json-schema/resolve-additional-types.html#L47
