### ISSUE TITLE
How does the `state_default` power-level play with `m.room.member` state events?

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix-spec#1005]
`state_default` defines the power level required to send state events:

> `state_default`
>
> The default level required to send state events. Can be overridden by the events key. Defaults to 50 if unspecified.
>
> *-- https://spec.matrix.org/v1.1/client-server-api/#mroompower_levels*

Yet, with a power-level of `0`, I can send a `m.room.member` state event when the `state_key` matches my own MXID and is a [valid](https://spec.matrix.org/v1.1/client-server-api/#mroommember) [transition](https://spec.matrix.org/v1.1/client-server-api/#room-membership).

But I can't send other state events even when the `state_key` matches my own MXID (403 forbidden, `Denying new event ... because 403: You don't have permission to post that to the room. user_level (0) < send_level (50)`)

---

Other related spot in the docs:

> State keys starting with an @ are reserved for referencing user IDs, such as room members. With the exception of a few events, state events set with a given user’s ID as the state key MUST only be set by that user.
>
> https://spec.matrix.org/v1.1/client-server-api/#state-event-fields

**Issue**

I assume `m.room.member` is a special case here but I can't find any docs explicitly calling out that it should be allowed regardless of what `state_default` is set as.

**Comment by turt2live** [comment]
Membership events are sent through the auth rules before the power level check: https://spec.matrix.org/v1.2/rooms/v9/#authorization-rules

**Comment by MadLittleMods** [comment]
Thanks @turt2live. This explains all of it!
