### ISSUE TITLE
Build warning from hugo 0.96

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-spec#1009]
Now that #986 is fixed, I tried to build with an up-to-date version of hugo again and huzzah, it works!

However, there's another (new?) warning that might turn into an error in a future version. Maybe this one can be fixed before the release that removes that funcionality 😄

> WARN 2022/03/29 16:10:23 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.

**Comment by turt2live** [comment]
This comes from our template, and I don't think we actually use it so even if it does break then oh well.

**Comment by zecakeh** [comment]
I don't see this particular warning anymore. I don't know if it was fixed when we updated docsy to v0.8.0, or before that. 

There are other warnings that are handled in https://github.com/matrix-org/matrix-spec/pull/1775.
