### ISSUE TITLE
Programmatically accept M_CONSENT_NOT_GIVEN

### ISSUE THREAD

**Issue by tobiasBora** [matrix-org/matrix-spec#1024]
**Suggestion**

When I register a guest user:
```
curl -XPOST https://matrix.org/_matrix/client/v3/register?kind=guest -d '{}'
```
and try to connect to a room I get an error `M_CONSENT_NOT_GIVEN` with a given url, but if I follow this url with curl it fails:
```
$ curl -XPOST 'https://matrix.org/_matrix/client/r0/rooms/YYYY:matrix.org/join?access_token=XXXXX -d '{}'
{"consent_uri":"https://matrix-client.matrix.org/_matrix/consent?u=56454643687&h=d7d42ff7c7aca589c334e3c45754547be8514f71b2aacf614847442e74c6ad2d","errcode":"M_CONSENT_NOT_GIVEN","error":"To continue using the matrix.org homeserver you must review and agree to our terms and conditions at https://matrix-client.matrix.org/_matrix/consent?u=56454643687&h=d7d42ff7c7aca589c334e3c45754547be8514f71b2aacf614847442e74c6ad2d."}
[leo@bestos:~]$ curl -XPOST 'https://matrix-client.matrix.org/_matrix/consent?u=56454643687&h=d7d42ff7c7aca589c334e3c45754547be8514f71b2aacf614847442e74c6ad2d' -d '{}'
<!DOCTYPE html>
<html lang=en>
  <head>
    <meta charset="utf-8">
    <title>Error 400</title>
  </head>
  <body>
     <p>Missing string query parameter &#x27;v&#x27;</p>
  </body>
</html>

```
If I open this url in my browser or in a `GET` way, I get an html form to fill, but unfortunately I'd prefer to fill this form programmatically (of course, I could parse the HTML, but it's not really a robust method as if the HTML changes, the parser will likely stop working). Would it be possible to provide a way to accept this form purely programmatically? The reason is that I'm writing some "bots" that use Matrix to signal WebRTC credentials in a room (to provide fully decentralized P2P communication), and I know my bot will follow the Matrix rules.

**Comment by turt2live** [comment]
It's intentional that this consent stuff requires user interaction, so if you want to get around it then I would suggest running your own server with less registration restrictions.
