### ISSUE TITLE
Prevent user from leaving room

### ISSUE THREAD

**Issue by MTrinkiesJr** [matrix-org/matrix-spec#1027]
Is there any way, maybe per PowerLevels, that prevents a user to leave the room?

I tried by setting the event "m.room.member" to "100", but the user can still leave the room.

Best regards 
Michael

**Comment by clmnin** [comment]
There is no way to prevent a user from leaving a room. What is the usecase where you want this feature?

**Comment by MTrinkiesJr** [comment]
We want to integrate Matrix with the Synapse server in our collaboration platform. So some rooms are "supervised" by our bot, which creates rooms automatically. We're developing our own client but the archtitecture is planned to be compatible to other clients like Riot aka Element.

So thanks for your information

**Comment by hKQwHW** [comment]
> There is no way to prevent a user from leaving a room. What is the usecase where you want this feature?

trapping everyone in a room with no escape

**Comment by richvdh** [comment]
you might be able to implement this via a synapse module. THere's certainly no way to do it in the federated protocol, nor would adding one be practical.
