### ISSUE TITLE
Server-server API does not describe what it means for a PDU to be valid

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-spec#1044]
> Whenever a server receives an event from a remote server, the receiving server must ensure that the event:
>
>   1.  Is a valid event, otherwise it is dropped.
>   2. ...

**Link to problem area**: https://spec.matrix.org/unstable/server-server-api/#checks-performed-on-receipt-of-a-pdu

**Issue**
Presumably "valid" means
- contains a `room_id` key
- the format of the event complies with the Event PDU Format in that room's room version.

**Comment by richvdh** [comment]
I think this is the same as https://github.com/matrix-org/matrix-spec/issues/365?

**Comment by DMRobertson** [comment]
> I think this is the same as #365?

Very much so. Thanks, I should have searched.
