### ISSUE TITLE
spec.matrix.org has several "Specification error: Example invalid or not present" errors.

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-spec#1071]
Specifically these are (at least, due to the way the spec shows and hides bits of it as you scroll, it's hard to get an accurate evaluation):
- https://spec.matrix.org/v1.1/client-server-api/#get_matrixclientv3thirdpartylocation
- https://spec.matrix.org/v1.1/client-server-api/#get_matrixclientv3thirdpartyprotocols
- https://spec.matrix.org/v1.1/client-server-api/#post_matrixclientv3roomsroomidreceiptreceipttypeeventid
- https://spec.matrix.org/v1.1/client-server-api/#post_matrixclientv3useruseridopenidrequest_token

**Comment by turt2live** [comment]
A bunch of these were fixed in the last half year - are you seeing them on unstable too?

**Comment by Half-Shot** [comment]
Seems to have been fixed since. I hope the updates get out eventually.

**Comment by turt2live** [comment]
well, they are fixed in v1.2 as far as I can tell - might need to update your autocomplete for the latest version of the spec? :p
