### ISSUE TITLE
Only one of `sdpMLineIndex` or `sdpMid` should be required in `Candidate`

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-spec#1078]
**Link to problem area**: https://spec.matrix.org/v1.2/client-server-api/#mcallcandidates

**Issue**
According to the WebRTC spec, both [`sdpMid`](https://w3c.github.io/webrtc-pc/#dom-rtcicecandidate-sdpmid) and [`sdpMLineIndex`](https://w3c.github.io/webrtc-pc/#dom-rtcicecandidate-sdpmlineindex) are nullable, but one of those two values must be set:

> If both the [sdpMid](https://w3c.github.io/webrtc-pc/#dom-rtcicecandidateinit-sdpmid) and [sdpMLineIndex](https://w3c.github.io/webrtc-pc/#dom-rtcicecandidateinit-sdpmlineindex) members of candidateInitDict are null, [throw](https://webidl.spec.whatwg.org/#dfn-throw) a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror). ([*source*](https://w3c.github.io/webrtc-pc/#dom-rtcicecandidate-sdpmlineindex))

Currently in the spec they are both marked as required.

**Expected behaviour**
Both fields should be nullable, explaining that at least one of the two is required.

In practice, both the [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk/blob/25afb7cb3cc612656458c00569cf03c42277aae2/src/webrtc/call.ts#L2234-L2240) and [Element Android](https://github.com/vector-im/element-android/blob/109b381e2edea9463f8e10629ce983146b1ea1c1/vector/src/main/java/im/vector/app/features/call/webrtc/WebRtcCall.kt#L928-L930) check that at least one of those is set, respecting the WebRTC spec, which makes this a spec bug rather than requiring an MSC.

**Comment by richvdh** [comment]
Still the case in https://spec.matrix.org/v1.6/client-server-api/#mcallcandidates.

@dbkr: can you confirm this?

**Comment by zecakeh** [comment]
Fixed with #1742.
