### ISSUE TITLE
Auth rule for restricted joins suggests an event should be signed by a user

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-spec#1092]
**Link to problem area**: https://spec.matrix.org/v1.2/rooms/v9/#authorization-rules

**Issue**

> 4. If type is m.room.member:
> 
>     1. If no state_key key or membership key in content, reject.
>     2. If content has a join_authorised_via_users_server key:
>         1. If the event is not validly **signed by the user ID denoted by the key**, reject.
> 
> 

Emphasis mine. I think it should read "signed by _the homeserver of_ the user ID denoted by the key".

**Comment by turt2live** [comment]
oops, yes. That would be my brain forgetting to write words it thought about.

Good spot!
