### ISSUE TITLE
 Is it possible that Matrix supports Solid?

### ISSUE THREAD

**Issue by rodriguezbrown** [matrix-org/matrix-spec#1146]
#### 1. feature-name
Is it possible that Matrix supports Solid?

#### 2.1 What is Solid?
Solid is a [specification](https://solidproject.org/TR/protocol) that lets people store their data securely in decentralized data stores called Pods. Pods are like secure personal web servers for your data.
- Any kind of information can be stored in a Solid Pod.
- You control access to the data in your Pod. You decide what data to share and with whom (be it individuals, organizations, and/or applications). Furthermore, you can revoke access at any time.
- To store and access data in your Pod, applications use standard, open, and interoperable data formats and protocols.

#### 2.2 Why should Matrix support Solid?
1. This allows for greater preservation of Matrix users data(messages, files) - which can make Matrix even better in terms of security policy and data privacy
2. There are a lot of apps that are running and working on Solid, I thought if the Matrix community would like to have Solid support as well - like a great success story

#### 2.3 notes
1. I would like to know if this idea is good or bad
3. My goal is to help two communities: Matrix, Solid
4. I didn't find any link, resource for this here in Matrix Community
5. I'm not promoting any company, service, product, solution, idea here - just adding the bibliographic reference links
 
#### 3. references
- https://solidproject.org/users/get-a-pod
- https://solidproject.org/apps
- https://solid.github.io/specification/
- https://forum.solidproject.org/

**Comment by turt2live** [comment]
This could probably be done with a protocol-level bridge given the similarity in data structures between the projects, though at a protocol level itself I don't really see Matrix adopting Solid at this juncture. Matrix also lets you store arbitrary blobs of data in a secure way, though is obviously less capable on the access controls for those blobs of data at the moment (unless you create a room per blob, which gets messy).

Leaving this open for others to bring forward feedback, however I don't think this is something we'd be looking at specifically. We'd certainly accept MSCs which bring us closer to Solid's model though, particularly the access control bits.

**Comment by rodriguezbrown** [comment]
@turt2live Hi! thank you for feedback ;D
