### ISSUE TITLE
Nameless DMs should not change to the room alias

### ISSUE THREAD

**Issue by Biep** [matrix-org/matrix-spec#1147]
Most DMs are nameless, so that for either party, the name of the other member shows.
Room aliases for DMs are quite useful - but not if they "grab" the room name, so that no longer the name of the other member shows.
For normal rooms this does not happen, so having the same (non-)behaviour for DMs should be a - very welcome - simplification of both the spec and of implementations.

**Comment by turt2live** [comment]
This is a client issue. The spec does not mandate any particular naming algorithm - it only suggests one.

**Comment by Biep** [comment]
I was asked to move it here.  It was in Element, but got closed there.

**Comment by turt2live** [comment]
I would assume that the client issue was closed incorrectly then.
