### ISSUE TITLE
Allow nameless general rooms

### ISSUE THREAD

**Issue by Biep** [matrix-org/matrix-spec#1148]
I have lots of rooms for three people, where only I am an admin, and where each of the members sees the other two as the name of the room. It seems it is no longer possible to create those - when clicking the OK button the room name field gets a red rim, and an error message appears. Until [variables in room names are possible](https://github.com/matrix-org/matrix-spec/issues/1150), please allow nameless rooms!

BTW: naming the room on creation and then deleting the name again later works - but it is an ugly work-around for something that ought to work out-of-the-box.  *Not* having an exception for the empty string for room names ought to simplify both spec and implementations.

**Comment by turt2live** [comment]
I would assume that the client issue was closed incorrectly then.

**Comment by richvdh** [comment]
for context, it would really help if you told us which issue you're saying was closed.

**Comment by Biep** [comment]
[This one](https://github.com/vector-im/element-web/issues/11167).

**Comment by richvdh** [comment]
ok thanks. I've reopened it.

**Comment by Biep** [comment]
Thanks!
