### ISSUE TITLE
Allow variables in room names

### ISSUE THREAD

**Issue by Biep** [matrix-org/matrix-spec#1150]
If room names can accept variables (especially %me% and %them%, and less importantly %you%), it would be possible to have rooms such as '%them% - work' vs. '%them% - private', which would translate into significant names on all sides.

See the discussion [here](https://github.com/vector-im/element-web/issues/8211) for more info.

**Comment by turt2live** [comment]
We'd probably handle this as https://github.com/matrix-org/matrix-spec/issues/188 rather than as variables. Variables are significantly more complex to represent than other semantics such as proper naming and pet names for rooms.

Closing in favour of https://github.com/matrix-org/matrix-spec/issues/188 or similar.

**Comment by Biep** [comment]
#188 is local, isn't it?  Part of the variable proposal is that the room maker can decide what the room will be named by default for *others* who see it.  Orthogonally, those others can locally rename it - that is a technically unrelated issue.
Or do I misunderstand #188?

**Comment by turt2live** [comment]
That ends up breaking a lot of the intention of room names, so pet names would be more preferred as an approach. If you're confident that it's not solved by #188, I would suggest opening an MSC rather than issue for proper discussion.

**Comment by Biep** [comment]
A simple example would be a supervisor who named the rooms "%you%, %them%, with the result that the supervisor is not mentioned in the name list, but is present and can take action when needed.  (E.g. parents supervising the "private" rooms in which their children have contact with unverified strangers.)
