### ISSUE TITLE
Message lifetimes

### ISSUE THREAD

**Issue by Biep** [matrix-org/matrix-spec#1151]
This issue, described [here](https://github.com/vector-im/element-meta/issues/364), has both a server and a client component.

**Comment by turt2live** [comment]
Closing in favour of MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/2228

**Comment by Biep** [comment]
Doesn't that do way less?  Or do you mean the rest of my proposal can be done client-only?
My proposal would be that delivery time can be done on the server - no need to have the client running at the moment that the server needs to deliver the message.  In fact, my reason for using future delivery may be precisely because I know my device will be off-line when delivery is needed.

**Comment by turt2live** [comment]
The MSC is the same sort of system you described in your other issue, so would recommend leaving any concerns you have with the MSC on the MSC.

**Comment by turt2live** [comment]
Matrix Spec Change: https://spec.matrix.org/unstable/proposals/

Moving issues to more appropriate repos is fine, however it doesn't guarantee that the issue stays open. For the spec we try to consider whether an issue is likely to be actioned or able to be actioned when deciding if it stays open or not. In this issue's case, we're not likely to action it specifically so have closed it - an MSC can of course be opened to better have a discussion around the feature, however in the spec repo here we're highly unlikely to engage on the subject.
