### ISSUE TITLE
/_matrix/media/v3/preview_url should specify an identifying server header 

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-spec#1159]
Some services may wish to opt out of prividing a URL preview, perhaps for practicality or privacy reasons. An example being a webhook service not wishing to trigger when the hook URL is provided in a room (ref https://github.com/matrix-org/matrix-hookshot/issues/395).

Right now, the way this is avoided is by looking at the User Agent for each homeserver implementation and filtering on that, but this will only serve to fragment the ecosystem going forwards.

I'd suggest a simple header like `X-Matrix-Preview` be included on requests to allow services to tailor their responses.

**Comment by richvdh** [comment]
I'm not super-enthusiastic about webpages that show different things depending on who is looking at them. 

> An example being a webhook service not wishing to trigger when the hook URL is provided in a room

isn't this better solved by making sure that the webhook only triggers on POST requests?

**Comment by Half-Shot** [comment]
Yeah, you make a good point. We've disabled GET support in hookshot as nobody was particularly enthusiastic about it.
