### ISSUE TITLE
If you have a SRV record in your matix.org domain pointing to home.example.com is useless to have to certificate both domains

### ISSUE THREAD

**Issue by ogarcia** [matrix-org/matrix-spec#1176]
Imagine that you have the following setup:
- Your homeserver is in `home.example.org` in standard port.
- Your domain is `matrix.org`.
- You have configured your domain with SRV records to point `_matrix._tcp.matrix.org` to `home.example.org` standard port.

According to the [matrix-federation-tester](https://github.com/matrix-org/matrix-federation-tester) your `home.example.org` has to expose a certificate that includes both domains `home.example.org` and `matrix.org`. According to [MSC1711](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/1711-x509-for-federation.md#interaction-with-srv-records) this is done to avoid a security problem caused by a DNS type MitM attack (that changes SRV record and point to `_matrix._tcp.matrix.org` to `mitm.hacker.com` for example), but if I can poison the DNS at that level, what prevents me from creating a TXT record to validate the main domain with letsencrypt and generate a new certificate?

IMHO. I believe that having to expose a certificate with both domains only makes server deployment more difficult than adding security.

**Comment by richvdh** [comment]
duplicate https://github.com/matrix-org/matrix-spec-proposals/issues/2533

> what prevents me from creating a TXT record to validate the main domain with letsencrypt and generate a new certificate?

For one thing, letsencrypt does its own DNS recursion based on the authoritative DNS servers, rather than relying on caches, which *significantly* raises the bar for an effective attack.

Our recommendation is not to use SRV records at all: `.well-known` files do not have this problem.
