### ISSUE TITLE
m.reaction documentation

### ISSUE THREAD

**Issue by catfromplan9** [matrix-org/matrix-spec#1177]
Hello, I'm not sure where to ask this, but the matrix spec seems to be missing information on m.reaction. My goal is to create a bot which can add reactions to messages containing specific words, but I haven't seen any documentation on the matrix spec. I used chromium dev tools and figured out roughly how the event works, but I've noticed that often my reaction will not be added to the message, and very rarely (the first time I add the reaction IIRC) it will. I'm never given an error code, and it appears to succeed giving me an event id of what I assume to be the reaction event. The id is the same every time for a given message, though. What could I be missing?

**Comment by clokep** [comment]
[MSC2677](https://github.com/matrix-org/matrix-doc/pull/2677) contains the information for it. (This is widely used even though the MSC hasn't been merged, but things followed a different process when that was initially written.)
