### ISSUE TITLE
details of knockable rooms are returned by `/hierarchy`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-spec#1186]
AIUI (based on https://github.com/matrix-org/matrix-spec/issues/1184#issuecomment-1195744344 - sorry, haven't tested):
 * if a room is invite-only, information on it is not returned by [`/hierarchy`](https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv1roomsroomidhierarchy), unless it is also world-readable (?)
 * however, if it is knockable, `/hierarchy` does return all sorts of information about the room, such as its topic.

Naively, as a user, I wouldn't expect that making a room knockable would expose information to non-members until they were accepted into the room (by sending them an invite). I'm worried that this will catch users off-guard.

**Comment by richvdh** [comment]
@clokep wrote:

> I think knock rooms are generally thought to be "findable" and that's why they're returned

Is that right? It's not obvious to me, and I'm not sure it would be obvious to a user. We have different controls for making rooms findable (in particular, [`GET/PUT  /_matrix/client/v3/directory/list/room/{roomId}`](https://spec.matrix.org/v1.3/client-server-api/#put_matrixclientv3directorylistroomroomid)).

**Comment by clokep** [comment]
> Is that right? It's not obvious to me, and I'm not sure it would be obvious to a user.

It seems rather obvious to me that if you add it to a space you want it to be findable by other users in a space.

> however, if it is knockable, `/hierarchy` does return all sorts of information about the room, such as its topic.

Note that the information returned is (mostly) the same as the room directory.

**Comment by richvdh** [comment]
> > Is that right? It's not obvious to me, and I'm not sure it would be obvious to a user.
> 
> It seems rather obvious to me that if you add it to a space you want it to be findable by other users in a space.

Yes, that's fair... though is it the case that you have to be a member of the space to call `/hierarchy` on it (or a parent space)?

Also, things like MSC3266 come along and want to apply the same logic to other endpoints.

> > however, if it is knockable, `/hierarchy` does return all sorts of information about the room, such as its topic.
> 
> Note that the information returned is (mostly) the same as the room directory.

Indeed. But my point is: adding it to the room directory is an explicit operation.

**Comment by Mikaela** [comment]
> however, if it is knockable, /hierarchy does return all sorts of information about the room, such as its topic.

I am confused on what information exactly and I agree with @clokep on knockable rooms being supposed to be findable so they can be knocked in the first place.

Personally I am using knocking in a couple of public world-readable rooms (and would use knock_restricted further once it's widely supported) as I find Matrix moderation tools lacking without an homeserver of my own and it gives me a bit control over do I want to let accounts screaming spambot/malicious in or even contact them first to ensure they are people.

In other protocols with knocking, IRC has separate controls on channel visibility and in Telegram if the link has a atUsername, it's publicly visible by typing part of that name and may also show the group history to everyone using a Telegram client before they select "request join".

**Comment by richvdh** [comment]
I don't feel like this is just a wart: it feels like it could really surprise users.

> I am confused on what information exactly

All the information returned by the `/hierarchy` endpoint. The spec is linked in the original description.

> Personally I am using knocking in a couple of public world-readable rooms 

If they are world-readable, there is no issue here. I'm specifically concerned about rooms that are knockable but *not* world-readable.

**Comment by richvdh** [comment]
@turt2live says:

> This is expected functionality imo. It's potentially a bit different if the room is `knock_restricted` (which is currently an OR condition, but I guess could be argued as an AND in this context), but generally a `knockable` room is considered public

**Comment by richvdh** [comment]
seems like nobody else considers this a problem, so I'll close it.
