### ISSUE TITLE
Search/context endpoint doesn't mention a `user_id`

### ISSUE THREAD

**Issue by S7evinK** [matrix-org/matrix-spec#1217]
**Link to problem area**: 
https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3search
https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3roomsroomidcontexteventid

**Issue**
Question came up in https://github.com/matrix-org/sytest/pull/1281
The `/search` endpoint doesn't specify a `user_id` in any of the response objects, yet Sytest is checking for the existence of this field.
I couldn't find `user_id` in any older spec version, so the question is what's the correct behavior. Do we need `user_id` (as currently returned by Synapse in `search_categories.room_events.results[]` and `search_categories.room_events.results[].context.events_before[]` (and `events_after`), or don't we need it?

Same question for `/context` returned values - Synapse returns a `user_id` in ClientEvent, while the spec doesn't mention it.

**Comment by richvdh** [comment]
Looking harder at this, it sounds like a (known) Synapse bug: https://github.com/matrix-org/synapse/issues/7925

**Comment by turt2live** [comment]
(for keywords: this will be an event format issue, as we're on v2 events at a minimum right now)
