### ISSUE TITLE
Spelling: s2s authorization header says 'receiving sender' instead of 'receiving server'

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1231]
https://spec.matrix.org/v1.3/server-server-api/#request-authentication

**Comment by saiprakash2** [comment]
Can I fix this issue?

**Comment by richvdh** [comment]
You don't need to ask for permission. Contributions are welcome. Please read https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst.
