### ISSUE TITLE
Commonmark ↔ GitHub Flavoured Markdown

### ISSUE THREAD

**Issue by weeman1337** [matrix-org/matrix-spec#1233]
I've read through the process and style docs. While doing that I found a small inconsistency:

- [`documentation_style.rst`](https://github.com/matrix-org/matrix-spec/blob/main/meta/documentation_style.rst#format) „Documentation is written in Commonmark markdown.“
- [Spec Change Proposal](https://spec.matrix.org/proposals/#process) „Create a first draft of your proposal using GitHub-flavored Markdown“

**Comment by turt2live** [comment]
This is somewhat intentional, as MSCs and the spec are split in two places. The documentation style document applies to the formal spec, and the MSC guidance is deliberately more permissive to reduce the barrier to entry on opening an MSC.

**Comment by richvdh** [comment]
Sounds like this is correct, then
