### ISSUE TITLE
No URL fragments available for to `section.rendered-data.defintion` in SS spec

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-spec#1242]
**Link to problem area**:

**Issue**

Compare 
![image](https://user-images.githubusercontent.com/8614563/191245909-5fd66f84-a11d-4b57-983a-3f9f814ed7c0.png)
with 
![image](https://user-images.githubusercontent.com/8614563/191245950-18c06406-5212-4f8e-8a7e-39d42ddce919.png)

The latter has no clickable anchor for `m.presence`.

The former is in a `section.rendered-data.event`; the latter is in a `section.rendered-data.definition`.

**Comment by richvdh** [comment]
This is fixed in unstable (https://spec.matrix.org/unstable/server-server-api/#mpresence), though there's no visible indication.
