### ISSUE TITLE
Info about aggregations not being required is outdated

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-spec#1262]
**Link to problem area**: https://spec.matrix.org/v1.4/client-server-api/#aggregations

**Issue**
This is the content of the info box:

> This specification does not currently describe any rel_types which require aggregation. This functionality forms a framework for future extensions. 

Which is not true anymore with the threads and event replacements added in v1.4.

I would have opened a PR directly to remove it but I'm not sure if it should instead be replaced by links to the corresponding sections of the spec for the different `rel_type`s, or something else.

**Comment by turt2live** [comment]
the intent was to delete the info box - good catch!

**Comment by zecakeh** [comment]
Fixed with #1263
