### ISSUE TITLE
Clients should clearly state which version of the spec they support (e.g. 1.2 vs 1.3)

### ISSUE THREAD

**Issue by opusforlife2** [matrix-org/matrix-spec#1264]
**Suggestion**

Clients should let the user know (in their About page, for example) what version of the spec they support, so that users can confidently start using features that that particular spec version provides.

For example, v1.3 includes Threads. Once a client like Nheko is fully compliant with Matrix v1.3, the user could see that and start using the feature without fear of fragmented support or implementation.

I thought about homeservers also advertising support for a particular Matrix version, but I don't know how useful or actionable that would be. If it is possible for the _client_ to detect what version of the spec is supported by the homeserver the user's account resides on, maybe that could be exposed alongside the client's own supported version.

**Comment by Mikaela** [comment]
I find this issue unrealistic. For example knocking was introduced in Matrix Spec 1.1 and is only implemented by Nheko to my knowledge. Does this mean Nheko is the only Matrix Spec 1.1 or newer compliant client and no client can claim to support anything later if they don't support 1.1?

* https://spec.matrix.org/v1.4/client-server-api/#knocking-on-rooms

**Comment by MTRNord** [comment]
Also imho it is totally valid for clients to opt out of implementing all features of spec. It may not fit the product, it may not be possible to implement easily on the platform or it may have a different ui/ux of the same feature making them to the user a different thing from how other clients have it anyway.

**Comment by turt2live** [comment]
We wouldn't make this a spec requirement that clients advertise their supported versions, however clients are encouraged to advertise their minimum supported spec versions so users can compare it to server versions, in cases of controlled deployments.

From a feature perspective, some parts of Matrix are required and others are optional: knocking happens to be non-optional in *receiving* knocks, but optional in *sending* knocks. Other features are less nuanced, and hopefully clarified in the spec itself. If not, please open an issue for each distinct case.

**Comment by opusforlife2** [comment]
Then maybe a client/feature matrix that shows which features that particular IM supports? (I'm only interested in IMs here) This way, users can choose between them based on what set of Matrix features they support. If the user needs to send knocks, they could choose Nheko based on that, from the example above. Alternatively, if, say, Element adds support for sending knocks, the user should be able to know that in case they want to wait for an update.

This matrix could be updated whenever a client starts supporting a new feature from the spec.

The basic idea is that the user should be able to use a feature knowing that their contacts use clients which also support that feature, without having to look at docs, release notes, or, heaven forbid, issues and PRs.

**Comment by turt2live** [comment]
That would be under the purview of the matrix.org site maintainers, and they already have such a thing: https://matrix.org/clients-matrix

**Comment by opusforlife2** [comment]
Ah. Is there a way to access that page from the website's homepage and not a direct link? I can't find it.

**Comment by turt2live** [comment]
matrix.org -> Discover -> Clients -> "Clients Matrix" link.
