### ISSUE TITLE
Matching remote users against the application service user namespace regex is a footgun

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix-spec#1272]
> Thanks for questioning this @erikjohnston. After thinking about this more and [asking in #matrix-spec](https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$c9mpH1UM80sEewLzXTQtpTGjeQYBkmd2M-gnvNnGrxQ?via=matrix.org&via=libera.chat&via=element.io), it indeed seems that there are *no valid use cases* for needing to specify a remote user in an application service's user namespace. By specifying local users, you will receive room events/presence updates from remote users anyhow.
> 
> As @Half-Shot put it, defining remote users is merely a footgun for which an Application Service may assume that it'll receive all events sent by that user, even though it will only receive events in rooms that are shared with a local user.
> 
> So by that logic, I'm fine with us defining (and limiting in the code) user namespaces to only cover local users. It would make sense to update the spec to include the same. Sorry for the run-around!
>
> *-- @anoadragon453, https://github.com/matrix-org/synapse/pull/14000*

---

This behavior has been updated in Synapse via https://github.com/matrix-org/synapse/pull/13958

**Comment by turt2live** [comment]
> So by that logic, I'm fine with us defining (and limiting in the code) user namespaces to only cover local users. It would make sense to update the spec to include the same. Sorry for the run-around!

The spec should be clear that it's only events the server has access to (thus rooms which are shared with that server) - changing the server-side code to *deny* remote users would be a spec violation, at least without an MSC to back it.

@anoadragon453

**Comment by turt2live** [comment]
> I agree. So not _denying_ shouldn't require an MSC.

Too many double negatives: At best, synapse can require a config option be set to allow the namespace, however it cannot take the functionality away on its own.

**Comment by turt2live** [comment]
ftr, https://github.com/matrix-org/synapse/pull/13958#discussion_r988369446 has more words on this (including the archeaology)

**Comment by MadLittleMods** [comment]
Created an MSC for this: [MSC3905](https://github.com/matrix-org/matrix-spec-proposals/pull/3905)
