### ISSUE TITLE
CI currently failing with broken links

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1336]
eg https://github.com/matrix-org/matrix-spec/actions/runs/3423504915/jobs/5702191261

**Comment by richvdh** [comment]
that seems to be because the CI for main sticks an `/unstable` on the front of all the links, which I think is easily accounted for in the link checker

**Comment by richvdh** [comment]
There are some actual broken links; Hugo seems to be generating links to RSS with too many `/unstable`s in the URL:

`<link rel="alternate" type="application/rss&#43;xml" href="/unstable/unstable/index.xml">`
