### ISSUE TITLE
Borked styling of list items under /register definition

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-spec#1352]
**Link to problem area**: https://spec.matrix.org/v1.4/client-server-api/#post_matrixclientv3register

**Issue**
![image](https://user-images.githubusercontent.com/8614563/202529147-9d8cfb33-8816-4531-8ddb-24d29132ccf2.png)

Was fine in 1.3, borked in 1.4 and 1.5.

**Comment by richvdh** [comment]
This seems to have been caused by https://github.com/matrix-org/matrix-spec/pull/1195/commits/473b30b2eb001d4d333f119f89c6bc89177165f0. The intention was to move the expander arrow on the summary section itself, but it has also had an effect on lists *within* the summary.

**Comment by richvdh** [comment]
> If it was up to me I'd just make the summary hold the `POST /_matrix/foo/v1/bar/` and nothing else. I usually minimise an endpoint's description if I don't care about it and want to see the rest of the document. Put differently: I think a `<summary>` whose height is about that of the viewport is excessive!

I think this is an easy change in https://github.com/matrix-org/matrix-spec/blob/main/layouts/partials/openapi/render-operation.html, if anyone fancies giving it a go! You might end up having to muck about with the CSS though.
