### ISSUE TITLE
matrix with orbit-db?

### ISSUE THREAD

**Issue by ghost** [matrix-org/matrix-spec#1378]
Hi everyone.

I would like to know what they think of the idea of ​​a decentralized database, distributed in the matrix as [orbit-db](https://github.com/orbitdb/orbit-db).

*What you all think of the idea of ​​a decentralized database, distributed in the matrix?*

**Comment by MTRNord** [comment]
This is basically what matrix at its core is. You got rooms as sections/tables, events as data. It's essentially a nosql database with some state handling on top.

**Comment by MTRNord** [comment]
Well as it is the core of matrix it obviously does. Without these semantics matrix wouldn't exist. There really isn't much to say about this. It's the fundamental concept used in matrix. Matrix is essentially nothing but a distributed database.

**Comment by MTRNord** [comment]
> I thought about adding orbit-db as a backend in the matrix.

That sounds like an implementation detail of a homeserver. Matrix itself doesn't specify what database is used. This is up to the individual implementation of a homeserver.
