### ISSUE TITLE
Extend msgtype m.text properties to control the notifications

### ISSUE THREAD

**Issue by wmwsagara** [matrix-org/matrix-spec#1388]
**Description:**

Please note, this is Matrix specification extend proposal.
Referring to: https://spec.matrix.org/v1.5/client-server-api/#mtext

Notification (eg. play a sound when a new message arrive) is desired but not always require for all messages in a room where automatic notifications is enabled.

Example, certain types of bot messages do not require notifications. 

Notifications on messages where notifications are not applicable, makes those messages a nuisance.

I propose a message-level notification control property, hypothetically named notification, where message sender controls the notifications.

If the notifications are enabled for a room, and:
1. If notification is true for the message, then client should render the notification (eg. play a sound).
2. If notification is false for the message, then client should not render a notification.

If the notifications are NOT enabled for a room:
3. Regardless of notification is true or false for the message, client should not render a notification.

**Comment by turt2live** [comment]
This is already possible with receiver-side push rules (sender-side push rules per-message would go against the threat model).

**Comment by KitsuneRal** [comment]
It's also worth noting here that there already is `m.notice` message type particularly intended for bot messages not worthy of notifications.

**Comment by wmwsagara** [comment]
@KitsuneRal thanks for highlight m.notice.

Objective of this proposal is to avoid generating push notifications to push notification providers (e.g. APNS, GCM) for messages a notification is not required. Also for desktops to not make any desktop-based notifications.

Example. Lets say I have 100,000 subscribers in a news feed (Stock/crypto). And I make a hourly market stats. 
That is, 2,400,000 push notifications per day has to generate by my Matrix server to the Apple and Google. I'm trying to avoid that.


m.notice: https://spec.matrix.org/v1.5/client-server-api/#mnotice

The m.notice does not specify Matrix server does not generate push notifications for such messages!

But m.notice seems an ideal candidate for this purpose. So the desktop Matrix clients can also honour m.notice to not disturb the user.

Can everyone agree on m.notice then and update the spec and Matrix server (if necessary)?

**Comment by clokep** [comment]
> The m.notice does not specify Matrix server does not generate push notifications for such messages!

See [the default push rule `.m.rule.suppress_notices`](https://spec.matrix.org/v1.4/client-server-api/#default-override-rules) which states that events with a `msgtype` of `m.notice` don't cause notifications.

**Comment by wmwsagara** [comment]
@clokep Yes, tested with m.notice. It does not generate push notifications and Element web client does not show any pop up or play sound either. This is exactly what I want. 

What is now left is to update the spec clearly mentioning that m.notice does not generate push notifications and web clients should not generate a notification either via pop up or sound.

Do you want me to create a document "Cosmetic issue" task to fix the documentation?

**Comment by KitsuneRal** [comment]
The notifications description in the spec already has the necessary words as mentioned above; and I personally see a lot of value in keeping separate the types of messages and the way they are notified about. You are free to make a pull request with your suggested changes, of course; be mindful that your particular usage of Matrix might not match that of others, so may want to be notified of `m.notice` events as well. Maybe it's best to leave the decision to users, as it is right now?

**Comment by wmwsagara** [comment]
I'm fine with m.notice with a default push rule not make push notifications.
