### ISSUE TITLE
Allow disabling room mentions (@room pings)

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-spec#1399]
**Suggestion**

If I understand correctly, currently the only way to opt-out of `@room` mentions is to disable all notifications for a room which isn't desirable. It's possible for a room to mention everone more often than fits individual preferences, so I think having an option to disable the notifications per-room would be desirable.

I asked about this at https://github.com/matrix-org/matrix-spec/issues/1074#issuecomment-1375861862 where I learned that `@room` has its own push rule and understand that the issue of replies to `@room` triggering notifications is addressed by https://github.com/matrix-org/matrix-spec-proposals/pull/3664. I also asked in spec room and [was informed that in Matrix it's preferable to open a duplicate rather than asking whether an issue exists.](https://matrix.to/#/%23matrix-spec%3Amatrix.org/%24fPZHJjWZEwUatxy4F_Dj6gi3YPdvLvOgTemyqd2Ae0E?via=pikaviestin.fi&via=libera.chat&via=0x1a8510f2.space&via=the-apothecary.club)

Other platforms with the feature of pinging everyone, such as Discord has the option to disable `@everyone` notifications per-room and I think Telegram also has option to disable notifications when moderator pinning a message selects "notify everyone".

**Comment by Mikaela** [comment]
I was able to locate this issue at https://github.com/vector-im/element-web/issues/12769 & https://github.com/vector-im/element-web/issues/17402, but as I am experiencing this in Nheko and FluffyChat too, I believe this to be a Spec issue rather than one with Element-Web.

**Comment by zecakeh** [comment]
It is doable with the spec, by adding a push rule like this in the `override` rules:

```json5
{
  "actions": [
    "dont_notify"
  ],
  "conditions": [
    {
      "key": "room_id",
      "kind": "event_match",
      "pattern": "!room_id:server.org"
    },
    {
      "kind": "event_match",
      "key": "content.body",
      "pattern": "@room"
    }               
  ]
}
```

The only catch is that it would prevent the default `.m.rule.contains_display_name` rule from triggering if the event content looks like this: `@room Alice is in Wonderland` (and the user's display name is `Alice`). But I doubt that's a behavior that someone would be counting on anyway.

**Comment by richvdh** [comment]
As @zecakeh says, I think this is something you can do with pushrules today, so this isn't a spec issue.

(There are plenty of things you *can't* do with pushrules, and I continue to believe the whole system needs replacing, but this isn't one of them).

Also note that `dont_notify` is a no-op (https://github.com/matrix-org/matrix-spec/issues/643)

**Comment by richvdh** [comment]
> If I understand correctly, currently the only way to opt-out of `@room` mentions is to disable all notifications for a room which isn't desirable. 

Also note that if you want to opt out of `@room` mentions altogether, you can do so by disabling the `.m.rule.roomnotif` pushrule.
