### ISSUE TITLE
server-server YAML files are not valid

### ISSUE THREAD

**Issue by afranke** [matrix-org/matrix-spec#14]
Running `node validator.js` on each of the files in `data/api/server-server` reveals errors in the following ones:

* [ ] invites-v1.yaml
* [ ] invites-v2.yaml
* [ ] joins-v1.yaml
* [ ] joins-v2.yaml
* [ ] keys_query.yaml
* [ ] keys_server.yaml
* [ ] knocks.yaml
* [ ] leaving-v1.yaml
* [ ] leaving-v2.yaml
* [ ] third_party_invite.yaml
* [ ] transactions.yaml
* [ ] user_keys.yaml

I haven’t taken the time to look into the files in the `definitions/` subdirectory, that should be checked too.

This is blocking publication (via CI) of the server-server OpenAPI JSON.

**Comment by zecakeh** [comment]
These files now pass validation, since they have been fixed before changing the validator in CI to Redocly-CLI.

Does that mean that the OpenAPI server-server definition should be generated in CI now?

**Comment by richvdh** [comment]
Interesting. Yes it should, but it currently is not: https://github.com/matrix-org/matrix-spec/blob/a147b977b3ab39d1ba44335edc0921558431de46/.github/workflows/main.yml#L95-L109

**Comment by richvdh** [comment]
closing in favour of https://github.com/matrix-org/matrix-spec/issues/1649
