### ISSUE TITLE
Idea: Ability to shutdown room

### ISSUE THREAD

**Issue by NebulaOnion** [matrix-org/matrix-spec#1403]
**Suggestion**
What would you like to see in Matrix? If your idea is vaguely complete enough, we
recommend submitting [an MSC](https://matrix.org/docs/spec/proposals) instead.

We may be able to modify the _m.room.tombstone_ state event so the "replacement_room" parameter is not mandatory anymore, if this is the case, clients could say something like "Room has been shutdown by the Admin".

I believe this should be easy to do as a predecessor to https://github.com/matrix-org/matrix-spec/issues/431 but without having to do complex spec changes.

**Comment by turt2live** [comment]
From a spec perspective, this would be accomplished by an admin/mod sending a message like "this room is no longer in use" and setting power levels such that no one can speak/react. 

#431 would handle the improved experience in this area.
