### ISSUE TITLE
Aggregations are confusing

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1405]
An `m.replace` event is aggregated by a server to (sometimes) create a bundle: none of these words are intuitive. 

See https://spec.matrix.org/v1.4/client-server-api/#server-side-aggregation-of-mreplace-relationships and related sections.

**Comment by richvdh** [comment]
IMHO the main problem here is the term "bundle", which I have long hated. (I think we iterated quite a lot on this on https://github.com/matrix-org/matrix-spec/pull/1062).

We should refer to either "an aggregation" if we are talking about the aggregation in general, or "bundled aggregation" if we specifically want to refer to the automatic inclusion in `unsigned`).

> An m.replace event is aggregated by a server to (sometimes) create a bundle: none of these words are intuitive.

No, all of the events which relate to a given event (`m.replace` included) are aggregated by a server to create an aggregation. Sometimes we include that aggregation along with the original event; that is called a bundled aggregation. `m.replace` isn't particularly special here.

**Comment by clokep** [comment]
As a bit of an contrary view -- what's the point of separating the "bundling" of it into a different term? Since the `/aggregations` endpoint was dropped from MSC2675 I don't think there's any other way of viewing an aggregation *besides* via it being in `unsigned`?

**Comment by turt2live** [comment]
fwiw, I find I keep swapping "bundle" and "aggregation" because "bundle" is more intuitive for what's happening (not everything *feels* aggregated, but everything *feels* bundled).
