### ISSUE TITLE
Room version grammar is inconsistent

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1408]
**Link to problem area**: https://spec.matrix.org/v1.5/rooms/#room-version-grammar

**Issue**
> Room versions MUST NOT be empty and SHOULD contain only the characters `a-z`, `0-9`, `.`, and `-`.

but then we go on to describe a grammar which doesn't honour the "SHOULD": is it legal to put emoji (for example) in room versions or not?

**Comment by richvdh** [comment]
> is it legal to put emoji (for example) in room versions or not?

what? no! why would it be?

**Comment by turt2live** [comment]
"SHOULD" implies the grammar is at most a suggestion.

**Comment by richvdh** [comment]
for links, afaict this wording was introduced by https://github.com/matrix-org/matrix-spec-proposals/pull/1773

**Comment by turt2live** [comment]
ftr, this appears to have actually come from https://github.com/matrix-org/matrix-spec-proposals/pull/1516 which links off to the MSC's google doc: https://docs.google.com/document/d/1urKgReoHqxX8R_XtySB17dPi-DZcKhqTEL2_s895Wz0/edit

That doc says:
> It is recommended that version strings are limited to the characters a-z, 0-9, . and -.

At the time, the MSC process was still very new and being figured out, so I can believe it was a misunderstanding that "It is recommended" was treated as a `SHOULD` instead of a recommendation to the SCT. Ie: it could feasibly be reworded to say "It is recommended that [the Spec Core Team consider] version strings be limited to...".
