### ISSUE TITLE
Lazy Events

### ISSUE THREAD

**Issue by devkral** [matrix-org/matrix-spec#1411]
Problem as far as I can see (I am not familiar with matrix but currently reading the blog and the specs):
big events (e.g. files) get synced between instances and can cause a lot of traffic and space usage (maybe there are some filter mechanics I am not aware of).
So my proposal is:
add a lazy Placeholder event (I call it later transfer event) with an transfer reference for events with a bigger size than a treshold.
The transfer event can then be used to request a transfer of the big event. This can be deprioritized and slowly transferred or just denied in case of not enough space, no permission of the client, …
If the transfer is denied/failed it can be retried.
If it succeeds the big event is now replacing the transfer event and returned for the requesting clients.

I am sorry for my imprecise language but I have no time to get into the matrix terminology.

**Comment by richvdh** [comment]
Possibly I'm missing a subtlety, but as far as I can tell this is pretty much how media events work today: if you want to send a file to another user, you don't encode it directly in the event, but send an [`m.file`](https://spec.matrix.org/v1.5/client-server-api/#mfile) message referencing the file.

**Comment by devkral** [comment]
thank you, missed this.
May I ask: how is the file stored? I see the mxc:// protocol.
Can you also store the file in e.g. ipfs?

**Comment by richvdh** [comment]
> Can you also store the file in e.g. ipfs?

Not at present, no. I suggest you search this repository for issues regarding IPFS.

Closing this issue as it seems to be resolved.
