### ISSUE TITLE
Extend msgtype m.text properties for presentation style microblogging

### ISSUE THREAD

**Issue by wmwsagara** [matrix-org/matrix-spec#1413]
Please note, this is a Matrix specification extend proposal.
Referring to: https://spec.matrix.org/v1.5/client-server-api/#mtext

**Background**:
We require to post microblogging-style posts to various news rooms that we maintain in a presentation style what the users are already used to (eg. Facebook, LinkedIn, etc.). 

Additionally, for certain breaking news, we want Matrix client to automatically read out the message body using TTS.

The microblogging-style should minimally and prominently carry a "Like Comment" section below the post to encourage users to engage with the post. See image below.

What is indeed missing is, in the current Matrix spec the ability to mark a post as microblogging. And mark certian posts to read out using TTS.

Further, we do not need a "Like Comment" section below every message. Of course, every message does not require to TTS out.

Sample microblogging post from LinkedIn:

![Screenshot from 2023-01-25 15-59-31](https://user-images.githubusercontent.com/94213268/214526841-cf10e61d-1b06-4f52-bd2b-d538001e954f.png)

**NOTE**: A post like above already can be achieved on Matrix using the ``formatted_body`` key. What's missing is the "Like Comment" section below the message.

**Problem**:
We have two types of rooms:

1. Group chat rooms: Where new messages and replies are both new messages to the room. There is no concept of threaded replies.

2. News Rooms: Every new message to the room is a new idea. Everyone has to reply in thread. Nothing new here, that's how they already use Facebook and LinkedIn. They don't create a new message as a reply. Replies are threaded.

Our requirement is, in News Rooms, we want every new message to be displayed with a "Like Comment" section below the message. But for the Group chat rooms, prominent display of "Like Comment" section is not even applicable. 

We want to indirectly encourage users to comment by showing the word "Comment". In Facebook and LinkedIn, the word "Comment" is directly in the line of sight.

The issue is, how does a client differentiate whether a given message is a group chat message or a news room message where "Like Comment" has to display from the start before anyone react or comment, also is it necessary to read out using TTS.

**Proposal**:
An optional new key, ``presentationStyle``, in addition to, ``body``, ``format``, ``formatted_body`` and ``msgtype``. 

The ``presentationStyle`` may be an enum and defaults to zero, including missing ``presentationStyle``, indicating client's default style for the m.text as of now.

Another value for ``presentationStyle`` is ``microblogging``, value may be ``1``.

Add ``1000`` to ``presentationStyle`` value indicates the message body requires to read out automatically using TTS. 

Of course, a bit map can be used for the ``presentationStyle``. I'm not sure how practical for the JavaScript/React programs to process bit maps.

The ``presentationStyle`` can be expanded in future to cover different presentation styles (eg. Facebook, LinkedIn, etc).

Example:
```
presentationStyle
0                   Default style, No TTS.
1                   Microblogging, Require "Like Comment" section below the post. No TTS.

1000                Default style, Read out the message body using TTS.
1001                Microblogging, Require "Like Comment" section below the post. Read out the message body using TTS.
```

Spec for the Like button:
1. Once hover on Like, pop up other options to react.

2. Default options for Like as follows: Like, Celebrate, Insightful, Curious, Funny, Love, Angry, Sad.

Of course, different clients may offer their specific presentation styles in different colours, fonts, and male or female voices, etc. 

But requirements for each ``presentationStyle`` value must be specified at Matrix spec level so that users know what to expect across various Matrix clients.

We're open to discuss other suggestions to achieve rich microblogging using Matrix.

**Comment by KitsuneRal** [comment]
1. As already mentioned in another issue of yours - please start using the [official process](https://spec.matrix.org/proposals/) to propose changes to Matrix. The repository for the proposals is at https://github.com/matrix-org/matrix-spec-proposals, not here; and there are certain guidelines that you're advised to follow up if you actually expect your changes to end up in the specification.
2. The case you describe prescribes certain visuals. The spec generally does not prescribe visuals, as client applications can vary greatly in the way they convey information (they might not even have the visual interface at all, but e.g., a voice interface).
3. Personally, I agree with the idea of hinting in certain messages that they best use a specialised interface; this would tie in nicely into the proposed [extensible events framework](https://github.com/matrix-org/matrix-spec-proposals/pull/1767) - again, if you are actually interested in getting your suggestions into the spec, I would suggest making your proposal based on this upcoming framework. You are welcome in [#matrix-spec](https://matrix.to/#/#matrix-spec:matrix.org) to discuss approaches and seek help.

**Comment by wmwsagara** [comment]
Sure will do.

**Comment by richvdh** [comment]
I'm going to close this as it seems to be in the wrong place.

**Comment by wmwsagara** [comment]
@KitsuneRal  @richvdh 

1. I'm sorry for posting a Matrix proposal to matrix-spec/issues. Not sure how it happened.
2. I sincerely cannot comply to the "Spec Change Proposals". I really do not have that much time in hand currently.
3. Can one of you submit this proposal to the matrix-spec-proposals in proper, I don't need any credit, so that others can benefit.
