### ISSUE TITLE
Missing `type` parameter on `/thumbnail` endpoint

### ISSUE THREAD

**Issue by clokep** [matrix-org/matrix-spec#1414]
**Link to problem area**: https://spec.matrix.org/v1.5/client-server-api/#get_matrixmediav3thumbnailservernamemediaid

**Issue**
Synapse [supports a `type` parameter](https://github.com/matrix-org/synapse/blob/b15f0758e59c8705ff50a414a5683286b5972381/synapse/rest/media/v1/thumbnail_resource.py#L72) (which defaults to `image/png` if not provided), this is not in the spec, but [has existed since this endpoint has](https://github.com/matrix-org/synapse/commit/cc84d3ea78eaf50c20ad84b3df99ecf4547e08a8#diff-1bfe097c081b9bbe9590487bb101362520157ce403bcc9c3d28a74635fd919aeR41).

matrix-media-repo does [not seem to support this](https://github.com/turt2live/matrix-media-repo/blob/88f0f671a811aab9fdd71a26990517a5939891ad/controllers/thumbnail_controller/thumbnail_resource_handler.go#L107-L120).

Dendrite [does not seem](https://github.com/matrix-org/dendrite/blob/c8935fb53f122b367eda61ec7811c406193d29ba/mediaapi/routing/download.go#L106-L110) to support this either, although [declares it uses a similar algorithm to Synapse](https://github.com/matrix-org/dendrite/blob/a84f50f4fb0963e15b6aca60f658bed45b779127/mediaapi/thumbnailer/thumbnailer.go#L51-L60) to find thumbnails.

**Expected behaviour**
Add the `type` parameter, as documented above.

As an aside, @Half-Shot rightly pointed out that this is what `Accept` headers are for?

**Comment by turt2live** [comment]
This is indeed what `Accept` headers are for. Given this feature has not proved useful in practice, it feels best described as a Synapse Feature rather than as Spec Omission - closing accordingly (an MSC can be opened to add it).

**Comment by clokep** [comment]
Thanks for the clarification. I've filed matrix-org/synapse#14913
