### ISSUE TITLE
Power level in the room

### ISSUE THREAD

**Issue by estylib** [matrix-org/matrix-spec#1419]
I'm unsure how I can get the one user's power level in the room. If, for example, I can get a list of users in the room, how can I know who from is a moderator?
 {your host}/_synapse/admin/v1/rooms/{roomId}

**Comment by richvdh** [comment]
Hi @estylib; I'm afraid we cannot provide support here.

If you're looking for help using the Synapse admin API then I suggest you start by reading the [documentation](https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/index.html) and if that doesn't help you might be able to find someone who can help in `#synapse:matrix.org`.
