### ISSUE TITLE
Remove authentication requirement for GET /_matrix/media/v3/config

### ISSUE THREAD

**Issue by catfromplan9** [matrix-org/matrix-spec#1428]
Title is pretty self explanatory. I feel like this info is not sensitive at all and it'd be useful to check this to decide if you want to use a server, because if its really low you might rather avoid signing up on that homeserver

**Comment by turt2live** [comment]
This is intentional, as it allows for per-user limits.

**Comment by catfromplan9** [comment]
> This is intentional, as it allows for per-user limits.

Perhaps the server's default limit could be displayed instead?

**Comment by turt2live** [comment]
unauthenticated users don't need to know the limit :)
