### ISSUE TITLE
ASCII art on room aliases on front of spec is misaligned

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix-spec#1430]
**Link to problem area**: https://spec.matrix.org/v1.5/#room-aliases

**Issue**
seems like there is a minor misalignment in the ASCII art. Probably some spaces have been eaten somewhere along the process.

![grafik](https://user-images.githubusercontent.com/1374914/218227234-3257cb46-ce7e-440b-9ec1-e0281634658f.png)

**Comment by yash08123** [comment]
**Fixed it, Does it look better now.**


![ASCII Fixed](https://user-images.githubusercontent.com/116726926/218245862-88297d9d-e5e2-4269-adad-8a5ef547b29c.png)
