### ISSUE TITLE
Add reporting functionality

### ISSUE THREAD

**Issue by mpldr** [matrix-org/matrix-spec#1459]
**Suggestion**
As the admin of a homeserver it would be nice to have a kind of "Report" message. This way clients could implement a "report" button which then sends a notification to the room's moderators (for which notifications can be handled differently from a simple ping). As another step for escalation, it might also be useful to add a "Report to Server Administrators" for illegal content, so it can be purged from from media repositories.

So to put it in not-wall-of-text-form:
- add a report message type `m.report` which can be sent to notify moderators without filling the history with pings
    - by default the report messages should only be displayed to people of a certain powerlevel
    - Example:
      ```xml
      <mx-report>
      @user:homeserver.tld has reported https://matrix.to/#/%21WjNnPFIjXXXXXXXXXX%3Amatrix.org/%24nBSjBXVXXXXXXXXXX-eHBcWnlaqfZYJpVXXXXXXXXXXX
      reason: I find this distasteful
      </mx-report>
      ```
- add a report message type `m.escalate` which can be sent from a certain powerlevel to notify server administrators of messages
    - escalation messages are handled by the server (sent as an email, sent to a dedicated room, etc.)

Limitations:
- admin-notification obviously only works in unencrypted rooms
- admins might be exposed to disgusting shit
- might be abused to spam admins and moderators (the latter can take appropriate action in their rooms, for the former I don't have a "simple" solution at hand)
- servers have to implement the escalation functionality

**Comment by richvdh** [comment]
https://spec.matrix.org/v1.6/client-server-api/#reporting-content ?

**Comment by turt2live** [comment]
There are things we want to do to improve how reports are handled in Matrix, though indeed the functionality you're describing is already in the spec.

**Comment by mpldr** [comment]
Thanks, I really didn't see that. Thank you for pointing me to it, I'll raise an issue with my client :)
