### ISSUE TITLE
Usage of filters needs clarification

### ISSUE THREAD

**Issue by BramvdnHeuvel** [matrix-org/matrix-spec#1494]
# Problem area

[Section 6 on Filtering](https://spec.matrix.org/v1.6/client-server-api/#filtering) offers very little detail on how filters work, and how they should be used by clients and homeservers.

Specifically, it is unclear what responses look like when the client uses a multitude of filters.

## Example: switching between filters

Suppose we paginate through events using the [`/messages`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3roomsroomidmessages) endpoint with filter `F1`, and we continue pagination using filter `F2`.

Suppose our timeline looks like this:

```
          matches filter F1
                  |
    /-------------|-------------\
    ↓             ↓             ↓
---[E1]---[E2]---[E3]---[E4]---[E5]---[E6]---[E7]--->
           ↑             ↑             ↑
           \-------------|-------------/
                         |
                 matches filter F2
```

Suppose we use [`/messages`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3roomsroomidmessages) with filter `F1`, which returns up to events `[E1]` and `[E3]` due to some imposed return limit. The homeserver would give use a token to keep paginating. If we were to do so, but instead used filter `F2` instead of filter `F1`, it is not clear whether the homeserver should:

- Reject the request because it uses a different filter.
- Start returning from event `[E4]`.
- Start paginating from `[E5]`, effectively glossing over `[E4]`.
- Decide for themselves how to paginate, depending on one's own implementation.

## Example: unfiltered sync with filtered backtrack

After a conversation in [#matrix-spec:matrix.org](https://matrix.to/#/#matrix-spec:matrix.org) starting from [here](https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$g_uLZylzNdDtr1M77iGUE3e8VPJ5UB2CKvb7EF8asjE?via=matrix.org), the conclusion from the conversation was that API endpoints aren't required to support filters other than the one the client uses on [`/sync`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3sync). If that is not the case, then seems to be unclear when filters can be applied.

# Use-case for supporting filter swapping

My [Matrix-Chess client](https://github.com/BramvdnHeuvel/Matrix-Chess) has players exchange `me.noordstar.game.chess.move` events to confirm having made moves. When a user logs in after a long time, they'll need to look back through the timeline to see if their opponent made a move. Instead of having to sift through (potentially long) conversations, it is better to use a [`/messages`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3roomsroomidmessages) request that only returns `me.noordstar.game.chess.move` events.

I want the [`/sync`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3sync) response to return all events, however. To show the activity of a room, I'd like to display a chat to the side that shows the most recent `m.room.message` events. I do not care about messages that were sent when the user was offline, however, and would like to skip them while looking for `me.noordstar.game.chess.move` events.

This means that the spec needs to support:

- [`/sync`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3sync) without a filter specified, and
- [`/messages`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3roomsroomidmessages) with a `me.noordstar.game.chess.move`-only filter specified.

Currently, it is unclear whether the spec supports that or not.

**Comment by richvdh** [comment]
Your first example is a duplicate of https://github.com/matrix-org/matrix-spec/issues/1304. The second I don't really understand, I'm afraid: could you open a separate issue explaining more clearly?

Clarifications to the spec in the form of pull-requests to this repository are very, very welcome.

**Comment by BramvdnHeuvel** [comment]
If the first example is a duplicate of #1304, then I think the second is too. The conversation that I linked to concluded that one cannot change their filter mid-pagination, but the issue you linked suggests that that _is_ possible.

**Comment by BramvdnHeuvel** [comment]
I wrote a [short whitepaper](https://github.com/noordstar/elm-matrix-sdk/blob/main/development/issues/Filters.md) on what's unclear concerning filters.

I guess that the main takeaway is that for the endpoints `/messages` and `/context`, the spec should declare that the batch token is placed in the timeline directly after the latest returned event. Could that be a clarification or does that require a spec change?

**Comment by richvdh** [comment]
I'm not following, I'm afraid.

Tokens represent a particular point in the timeline. Which events you have chosen to see via your filter have no bearing on the timeline, nor on tokens which point into it.

**Comment by BramvdnHeuvel** [comment]
The whitepaper presents the following example for the [`/messages`](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3roomsroomidmessages) endpoint:

![afbeelding](https://github.com/matrix-org/matrix-spec/assets/43719024/dbe13b30-e6c6-49b3-b56e-ac8f07abef78)

At what point in the timeline should the `end` batch token be for the **Circles only** example shown in this diagram?

I think the spec does not state where this should be - but not specifying can lead to differences among implementations.

**Comment by BramvdnHeuvel** [comment]
That sounds fair. I will close this issue and keep an eye on the other one.
