### ISSUE TITLE
Room tags request body `order` nullability

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/matrix-spec#1504]
**Link to problem area**:

https://spec.matrix.org/v1.6/client-server-api/#put_matrixclientv3useruseridroomsroomidtagstag

**Issue**

It seems that order is really an optional field, I have a bunch of rooms with no tag metadata
<img width="255" alt="image" src="https://user-images.githubusercontent.com/2403652/235109110-9521965e-9ca9-4487-b86a-849223eb84a4.png">

Is the spec wrong? Should the field be optional? The js-sdk types demand `order` which causes react-sdk type fails in strict mode.

**Comment by KitsuneRal** [comment]
I don't see `order` being required in the spec, neither at the link you gave, nor elsewhere?

**Comment by t3chguy** [comment]
Oh derp, I somehow mixed up whether we doc things being optional or required. Thanks for the hint of sanity @KitsuneRal
