### ISSUE TITLE
Naming consistency in the type names.

### ISSUE THREAD

**Issue by Firstbober** [matrix-org/matrix-spec#1505]
**Link to some problem areas**:
https://spec.matrix.org/v1.6/client-server-api/#syncing
https://spec.matrix.org/v1.6/client-server-api/#post_matrixclientv3joinroomidoralias

**Issue**:
There are currently at least a few of the type names which collide with other in spec on the terms of style, `Third Party Signed`, `Invited Room`, `Joined Room` etc. which have spaces and others in the spec don't, like `StrippedStateEvent`, `ClientEventWithoutRoomID`, `UnsignedData`. This style, without spaces, represents the majority of type names in the spec currently. 

I think we should make them all in one style, with spaces or without them.

**Comment by richvdh** [comment]
Agreed.

These titles come from the OpenAPI data (for example, https://github.com/matrix-org/matrix-spec/blob/main/data/api/client-server/definitions/third_party_signed.yaml#L15), and a PR to fix them would be welcome.

I think this is closely related to #827 and I'm going to close it as a duplicate.
