### ISSUE TITLE
Adopt Semantic Versioning

### ISSUE THREAD

**Issue by OattyGengar** [matrix-org/matrix-spec#1523]
**Suggestion**
The Matrix Spec does not currently use [semver](https://semver.org/) for its versions. Semver is standardized, well-understood, and widely adopted in many FOSS projects. Matrix should adopt and migrate to semantic versioning in all locations where versioning is used.

**Comment by turt2live** [comment]
We don't use semantic versioning for a number of reasons, largely described by the MSC which introduced our current versioning approach: https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/2844-global-versioning.md#alternatives
