### ISSUE TITLE
`m.get_login_token` capability is not documented

### ISSUE THREAD

**Issue by hughns** [matrix-org/matrix-spec#1547]
**Link to problem area**:
https://spec.matrix.org/v1.7/client-server-api/#get_matrixclientv3capabilities

**Issue**
https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv1loginget_token makes reference to a `m.get_login_token` capability. However, the capability section 5 does not describe the capability: https://spec.matrix.org/v1.7/client-server-api/#get_matrixclientv3capabilities

<img width="2071" alt="image" src="https://github.com/matrix-org/matrix-spec/assets/6955675/75eaa2ed-f83b-4b8c-9133-219e79c07da6">

**Expected behaviour**

The `m.get_login_capability` should be described in section 5.

**Comment by richvdh** [comment]
for archaeology: the new endpoint was added in https://github.com/matrix-org/matrix-spec/pull/1530, which appear to have forgotten to document the capability in section 5.

When fixing this, don't forget to add it to the table at https://spec.matrix.org/v1.7/client-server-api/#_matrixclientv3capabilities_capabilities.
