### ISSUE TITLE
Server name resolution uses bullets instead of numbers for Step 3

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1567]
**Link to problem area**: https://spec.matrix.org/v1.7/server-server-api/#resolving-server-names

**Issue**
It's super minor, but under Step 3 should be a numbered list given we care about order.

**Comment by mohit1523** [comment]
Sir, I can solve issue #1567.

It just requires a minor change in the code and the issue will be resolved .
So, please guide me how I can make the changes in the repository.

Thank You

**Comment by richvdh** [comment]
> So, please guide me how I can make the changes in the repository.

These guides may be helpful:

https://opensource.guide/how-to-contribute/#opening-a-pull-request
https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst

**Comment by mohit1523** [comment]
@richvdh sir, I am unable to find the file in the repository via which I am able to solve this issue. 
So please can you mention the filename so that it will be really helpful for me to solve the issue.

**Comment by richvdh** [comment]
Previously you said:

> It just requires a minor change in the code and the issue will be resolved .

Sounds like you already know what needs changing? No? 

It's not very hard to find: https://github.com/search?q=repo%3Amatrix-org%2Fmatrix-spec+%22If+the+hostname+is+not+an+IP+literal%22&type=code

I feel like you're wasting people's time.

**Comment by mohit1523** [comment]
@richvdh Sir, I know about the changes to be made but I was having some trouble in finding the _file_ that is why I ask you.

I have solved the **_**issue #1567**._**

Please review it.

**Comment by mohit1523** [comment]
@richvdh sir, I have solved the **issue #1567**. 
_Please review it._

**Link :-** https://github.com/matrix-org/matrix-spec/pull/1623
