### ISSUE TITLE
Server name resolution talks about a default port in Step 4, during SRV record resolution

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1568]
**Link to problem area**: https://spec.matrix.org/v1.7/server-server-api/#resolving-server-names

**Issue**
SRV records are best described at https://www.cloudflare.com/learning/dns/dns-records/dns-srv-record/

Considering an SRV record is supposed to always have a port, does it make sense to default to port 8448? The equivalent step under .well-known (Step 3.3) makes no mention of a default port.

We should unpick this and decide if there's a default port or not, then apply it to both steps.

**Comment by richvdh** [comment]
You're right, this is a nonsense. There is no need for a default port in step 4.
