### ISSUE TITLE
Update .well-known IANA registration 

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1575]
https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

The spec links no longer point to the endpoints they intend to.

**Comment by richvdh** [comment]
It's even worse currently: due to a matrix.org website update this morning, they are 404s. But hopefully that is temporary and will be fixed soon.

**Comment by thibaultamartin** [comment]
What @richvdh refers to has been fixed! The following urls are not 404ing anymore

- https://spec.matrix.org/latest/client-server-api/#well-known-uri
- https://spec.matrix.org/latest/server-server-api/#get-well-known-matrix-server

**Comment by turt2live** [comment]
thanks! Now we just need to update the URLs with IANA

**Comment by turt2live** [comment]
We should be linking to `/latest`, unfortunately. Otherwise people will get "wrong" copies of the spec if they visit through the IANA angle. 

Comments in the code would be good, but also maybe we just don't change entire spec platforms too often :p

**Comment by turt2live** [comment]
modification request submitted: https://github.com/protocol-registries/well-known-uris/issues/33
