### ISSUE TITLE
Register Server Port at IANA

### ISSUE THREAD

**Issue by 6543** [matrix-org/matrix-spec#1576]
At the moment only [Wikipedia](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) has 8090, 8008 and 8448 listed.

If you look at the [Service Name and Transport Protocol Port Number Registry](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) it only shows
 * **8446-8449** as [Unassigned](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=111)
* **8090** as [opsmessaging](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=109)
* **8008** as [http-alt](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=108)

The suggestion Would be to get 8448 or the whole range, depending on future needs ...

**It would be good to catch this Port officially so others cant.**
(*Service names are assigned on a first-come, first-served process, as documented in [RFC6335].*)

**Comment by turt2live** [comment]
reopened because we should register it

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-spec/issues/1577 tracks using port 443 instead

**Comment by turt2live** [comment]
Registration request has been submitted

**Comment by turt2live** [comment]
8448 is now registered for the foundation to use.

![image](https://github.com/matrix-org/matrix-spec/assets/1190097/03eb2825-933d-47b4-929d-330454069928)

**Comment by 6543** [comment]
awesome :)
