### ISSUE TITLE
The spec doesn't build in Hugo v0.114.1

### ISSUE THREAD

**Issue by akirk** [matrix-org/matrix-spec#1586]
**Link to problem area**: -

**Issue**
The instructions for building the spec fail with a modern hugo version. For example, Homebrew on macOS installs `hugo v0.114.1+extended` where building fails with this error message:

> Error: error building site: failed to render shortcode: "matrix-spec/content/client-server-api/_index.md:2488:1": failed to render shortcode "http-api": failed to process shortcode: "matrix-spec/layouts/shortcodes/http-api.html:26:3": execute of template failed: template: shortcodes/http-api.html:26:3: executing "shortcodes/http-api.html" at <partial "openapi/render-api" (dict "api_data" $api_data "base_url" $base_url "path" $path)>: error calling partial: "matrix-spec/layouts/partials/openapi/render-api.html:36:11": execute of template failed: template: partials/openapi/render-api.html:36:11: executing "partials/openapi/render-api.html" at <partial "openapi/render-operation" $operation_params>: error calling partial: execute of template failed: template: partials/openapi/render-operation.html:67:3: executing "partials/openapi/render-operation.html" at <partial "openapi/render-request" (dict "parameters" $operation_data.parameters "request_body" $operation_data.requestBody "path" $path "anchor_base" $anchor)>: error calling partial: "matrix-spec/layouts/partials/openapi/render-request.html:45:26": execute of template failed: template: partials/openapi/render-request.html:45:26: executing "partials/openapi/render-request.html" at <partial "json-schema/resolve-refs" (dict "schema" $json_body.schema "path" $path)>: error calling partial: "matrix-spec/layouts/partials/json-schema/resolve-refs.html:43:28": execute of template failed: template: partials/json-schema/resolve-refs.html:43:28: executing "partials/json-schema/resolve-refs.html" at <partial "json-schema/resolve-refs" (dict "schema" $value "path" $path)>: error calling partial: "matrix-spec/layouts/partials/json-schema/resolve-refs.html:43:28": execute of template failed: template: partials/json-schema/resolve-refs.html:43:28: executing "partials/json-schema/resolve-refs.html" at <partial "json-schema/resolve-refs" (dict "schema" $value "path" $path)>: error calling partial: "matrix-spec/layouts/partials/json-schema/resolve-refs.html:43:28": execute of template failed: template: partials/json-schema/resolve-refs.html:43:28: executing "partials/json-schema/resolve-refs.html" at <partial "json-schema/resolve-refs" (dict "schema" $value "path" $path)>: error calling partial: "matrix-spec/layouts/partials/json-schema/resolve-refs.html:58:43": execute of template failed: template: partials/json-schema/resolve-refs.html:58:43: executing "partials/json-schema/resolve-refs.html" at <append $resolved>: error calling append: reflect: call of reflect.Value.Type on zero Value

I tested also Hugo 0.113.0 and it successfully builds there, so something specifically in the v0.114.0 release broke it (and v0.114.1 is still broken).

**Expected behaviour**
The spec should build without warning in recent Hugo versions. Likely a number of other problems also need to be resolved, for example #1544.

**Comment by richvdh** [comment]
This appears to be due to the `[null, "m.space"]` in https://github.com/matrix-org/matrix-spec/blob/v1.7/data/api/server-server/public_rooms.yaml, which seems to be upsetting the `append` in https://github.com/matrix-org/matrix-spec/blob/v1.7/layouts/partials/json-schema/resolve-refs.html#L58.

I suspect it has been introduced by https://github.com/gohugoio/hugo/pull/11104 which means that `append` now does a `reflect.ValueOf` on its inputs.

**Comment by richvdh** [comment]
Raised upstream as https://github.com/gohugoio/hugo/issues/11180

**Comment by richvdh** [comment]
... and apparently already fixed upstream

**Comment by richvdh** [comment]
Hugo v0.115 is now released. Could somebody check if the spec now builds ok?

**Comment by richvdh** [comment]
Tested with v0.115.1 - seems fine
