### ISSUE TITLE
Support request-side hint for disabling url preview for API's m.room.message

### ISSUE THREAD

**Issue by Kaned1as** [matrix-org/matrix-spec#1588]
### Description

Enhancement request to support request-side hint for disabling url preview for Client-Server API's m.room.message (text or notice).

My use-case is the bot that periodically sends notifications to certain chat. While I want URL previews be generally available for this chat, I don't want these bot messages to show URL preview.

I see it as smth like this:
```json
{
  "msgtype": "m.text",
  "format": "org.matrix.custom.html",
  "formatted_body": "<a href='...'>text</a>",
  "body": "[md text](md link)",
  "hints": ["m.hint.no_preview"]
}

```
or this
```json
{
  "msgtype": "m.text",
  "format": "org.matrix.custom.html.no.preview",
  "formatted_body": "<a href='...'>text</a>",
  "body": "[md text](md link)",
}

```

If I need to create issue somewhere else, please advise.
Thanks in advance.

### Steps to reproduce

N/A

### Version information

The one currently deployed on public instance of matrix.org

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/matrix-spec/issues/221

**Comment by anoadragon453** [comment]
@Kaned1as Note that this was moved from the Synapse issue tracker to here, as such a feature will require guidance from the Matrix spec before being implemented in any Matrix homeservers or clients.

To move this forwards, consider reading https://github.com/matrix-org/matrix-spec-proposals/pull/2385 and sending feedback, as well as asking for an experimental implementation in a Matrix client to help prove the proposal. Also see the [Matrix Spec Process](https://github.com/matrix-org/matrix-spec-proposals#the-matrix-spec-process) for an explanation of how this all works.

**Comment by Kaned1as** [comment]
understood, thank you.
