### ISSUE TITLE
 /_matrix/identity/v2/account/register  Specification error: Example invalid or not present

### ISSUE THREAD

**Issue by grinapo** [matrix-org/matrix-spec#1589]
**Link to problem area**:
https://spec.matrix.org/v1.1/identity-service-api/#post_matrixidentityv2accountregister

**Issue**
Example missing/bad. Ugly red rectange instead. Not even rounded corners. I'm scared.

**Comment by MTRNord** [comment]
This probably was fixed long ago. You linked to a really old version of spec. Current version at https://spec.matrix.org/v1.7/identity-service-api/#post_matrixidentityv2accountregister seems fine.

**Comment by grinapo** [comment]
Interesting that google found that but you're right.
