### ISSUE TITLE
login with key

### ISSUE THREAD

**Issue by Pantyhose-X** [matrix-org/matrix-spec#1605]
**Remove:** 3rd Party IDs (3PIDs) such as email addresses, phone numbers, Facebook accounts to authenticate, identify and discover users on Matrix. 

## will solve the following problems ##
* I have an account with **element**, but **Homeserver** is blocked, I have to go to a new **Homeserver** to create an account, which will cause all my contacts and groups to be gone,

* All federated **Homeserver** must sync account keys, I don't need to go to a new **Homeserver** to re-register an account,
I only need to enter the key in the new **Homeserver** to log in, and my contacts and groups still exist. This also solves the problem that **Homeserver** does not open user registration

* **Homeserver** blockage is severe In countries (China Iran North Korea etc.), the only solution users must use VPN but VPN is very expensive. Maybe matrix can build a network similar to [Tor Snowflake](https://snowflake.torproject.org/)

**Comment by KitsuneRal** [comment]
Looks like you want to _change everything_ in the way authentication is done in Matrix :)

There are many common people using Matrix that do not need to circumvent homeserver blocking - authenticating using an external identity is the best and sometimes the only reasonable way for them. Matrix is made to be flexible and applicable to different use cases; removal of 3PIDs is certainly out of question. 

What you seem to actually want is user account portability - this is a much requested feature but is very hard to get right. You're welcome to follow the ongoing work in [MSC2787](https://github.com/matrix-org/matrix-spec-proposals/pull/2787).
