### ISSUE TITLE
`m.ignored_user_list` definition refers to undefined type `Ignored users`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-spec#1610]
**Link to problem area**: https://spec.matrix.org/v1.7/client-server-api/#mignored_user_list

**Issue**
Have to currently infer the structure of `Ignored users`.

While we're at it, it's not clear what the point of this being a map is---what are the values? Seemingly empty JSON objects? Is this just so we have room to expand this in the future?

**Comment by clokep** [comment]
> While we're at it, it's not clear what the point of this being a map is---what are the values? Seemingly empty JSON objects? Is this just so we have room to expand this in the future?

The values are ignored, but I think an empty dict is what is supposed to be sent.

I came to the same conclusion that it is for future needs, if necessary.

**Comment by zecakeh** [comment]
Note that the fact it is not rendered is the same reason as in #1343, `patternProperties` is currently not supported on the rendering side.

**Comment by zecakeh** [comment]
I believe this was fixed in #1637. It now renders as: `{string: object}` ([see in v1.9](https://spec.matrix.org/v1.9/client-server-api/#mignored_user_list)).

Unless that representation is not satisfactory either?

**Comment by DMRobertson** [comment]
Thanks!
