### ISSUE TITLE
Adding support for subpaths

### ISSUE THREAD

**Issue by Thatoo** [matrix-org/matrix-spec#1625]
[For what I understand](https://github.com/gary-kim/riotchat/pull/369), the matrix protocol requires matrix media repository to start with `/_matrix/media`, sub-paths are unfortunately not possible.
And this is forbidding file hosting project such as Nextcloud to become a matrix media repository and thus forbid riochat (Element for Nextcloud) to "Add matrix share" and truly integrate Element within Nextcloud.
 
[For what I understand](https://github.com/matrix-org/matrix-spec/issues/693#issuecomment-1055968074) : the spec doesn't allow subpathing given all the paths are defined as `/_matrix`, and thus are absolute.
Treating them as absolute is overly restrictive, isn't it?

It makes a problem for media repository (mentioned above) but also for [Pusher](https://github.com/matrix-org/matrix-spec/issues/677#issuecomment-729773097).

Would it be possible to change the spec in order to make subpaths discovering in .well-known files?

**Comment by turt2live** [comment]
Resolving https://github.com/gary-kim/riotchat/pull/369 I think will resolve this issue, or at least provide a better direction for such an improvement request.
