### ISSUE TITLE
Is it legal to send `is_falling_back` when `rel_type` is missing/not a thread?

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1631]
**Link to problem area**: https://spec.matrix.org/v1.8/client-server-api/#fallback-for-unthreaded-clients

**Issue**
![image](https://github.com/matrix-org/matrix-spec/assets/1190097/c05362c6-3462-4a7a-acf8-2965f5062058)

**Comment by richvdh** [comment]
My impression is that it's not exactly illegal, but it would be meaningless, as would be sending: `"i_am_a_teapot": false` ? The spec only mentions it in conjunction with `"rel_type": "m.thread"`.

**Comment by richvdh** [comment]
I'm not really sure where in the spec we could put clarifying text for this, or even that we should. There is absolutely no implication in the spec that the presence of `is_falling_back` implies that the event is a thread.

I don't think we should do anything here.
