### ISSUE TITLE
`m.room.name`'s `name` field is marked as required but is described as possibly absent

### ISSUE THREAD

**Issue by zecakeh** [matrix-org/matrix-spec#1632]
**Link to problem area**: https://spec.matrix.org/v1.8/client-server-api/#mroomname

**Issue**
The schema of the event says that the `name` field is required. The description of the event says that the same field can be "absent, null, or empty".

**Expected behaviour**
It should either be required or not.

For context, Synapse doesn't accept that a client sends this event if the field is not a string.

**Comment by richvdh** [comment]
>  The description of the event says that the same field can be "absent, null, or empty".

I'm not sure it says exactly that?

As with all Matrix events, implementations have to behave sensibly when they receive a *malformed* event. The text I think you are referring to provides some guidance on what implementations should do if they receive an `m.room.name` event which is (incorrectly) missing a `name` property.

**Comment by zecakeh** [comment]
Ah indeed, I did not understand it like that.
