### ISSUE TITLE
Spec formats items with multiple types as an array

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-spec#1675]
**Link to problem area**:
https://spec.matrix.org/unstable/client-server-api/#_matrixclientv3pushrules_pushcondition

**Issue**

![image](https://github.com/matrix-org/matrix-spec/assets/1389908/1068b711-bed2-406e-a87a-887d73e121e2)

It is not an array; rather it should be one of `string`, `integer`, `null` or `boolean`. In other parts of the spec (eg [`PushRule`](https://spec.matrix.org/unstable/client-server-api/#_matrixclientv3pushrules_pushrule)) we represent this with a `|` character. (Note that in the case of `actions`, it is *actually* an array of `string`s or `object`s, so the `[]` are correct in that case.)

**Comment by richvdh** [comment]
The source for this definition is [here](https://github.com/tusooa/matrix-spec/blob/c335f2b9413a8ed331972ff499788c52182d1c0a/data/api/client-server/definitions/push_condition.yaml#L47). 
Per https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0, this "array of types" became valid in OpenAPI 3.1.0.

It looks like we need to update https://github.com/matrix-org/matrix-spec/blob/main/layouts/partials/openapi/render-object-table.html to handle it.

**Comment by zecakeh** [comment]
This was fixed by #1789.
