### ISSUE TITLE
Media download endpoints do not describe a 404 response

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-spec#1678]
**Link to problem area**: 
- https://spec.matrix.org/v1.8/client-server-api/#get_matrixmediav3downloadservernamemediaid
- https://spec.matrix.org/v1.8/client-server-api/#get_matrixmediav3downloadservernamemediaidfilename
- https://spec.matrix.org/v1.8/client-server-api/#get_matrixmediav3thumbnailservernamemediaid

**Issue** 
These don't mention 404 return code, despite this being reasonable and obvious.

**Expected behaviour**
Synapse returns 404 in some situations:  Synapse does this, e.g. https://github.com/matrix-org/synapse/blob/999bd77d3abb7b0a4430f31f5912956c3bc100ee/synapse/media/media_repository.py#L510

so we should update the spec text to reflect this.

**Comment by turt2live** [comment]
Merging into https://github.com/matrix-org/matrix-spec/issues/1122

**Comment by DMRobertson** [comment]
Thanks---I should have searched (harder?).

**Comment by turt2live** [comment]
no worries - it took me several searches 😅 

could have sworn we had an issue for it already, but turns out it was for thumbnails only (now fixed)
