### ISSUE TITLE
NPM publishing for emoji translations still broken

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1681]
https://github.com/matrix-org/matrix-spec/actions/runs/7036057140/job/19147844038

Previous fix: https://github.com/matrix-org/matrix-spec/pull/1648

**Comment by turt2live** [comment]
Looks like it's still failing: https://github.com/matrix-org/matrix-spec/actions/runs/8393215998

New error, though.

**Comment by turt2live** [comment]
Another quarter, another error message: https://github.com/matrix-org/matrix-spec/actions/runs/9601021575/job/26478620278

**Comment by t3chguy** [comment]
![image](https://github.com/matrix-org/matrix-spec/assets/2403652/8b353e49-70e0-4249-8b8d-d831c25399de)

Looks like a missing secret, I lack access to investigate

**Comment by turt2live** [comment]
yea, we forgot to add the `NPM_TOKEN` secret, oops. Adding it and re-running the job did the thing: https://www.npmjs.com/package/@matrix-org/spec/v/1.11.0
