### ISSUE TITLE
Some of the event-schema yaml files dont actually are yaml

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix-spec#1694]
**Link to problem area**: https://github.com/matrix-org/matrix-spec/tree/main/data/event-schemas/schema

**Issue**
Some files in this folder contain json instead of yaml despite the fileending implying yaml

**Expected behaviour**
They should probably be converted to yaml.

**Comment by richvdh** [comment]
YAML is a superset of JSON: any valid JSON is also valid YAML.

**Comment by turt2live** [comment]
Closing as intended behavior.
