### ISSUE TITLE
Conflicting use of PublicRoomsChunk for space hierarchy over federation

### ISSUE THREAD

**Issue by Kladki** [matrix-org/matrix-spec#1729]
**Link to problem area**:
https://spec.matrix.org/v1.9/server-server-api/#get_matrixfederationv1hierarchyroomid

**Issue**
There are two different types with the name `PublicRoomsChunk`, with the only difference being that the latter has a `children_state` field which the other doesn't. In [ruma](https://ruma.io), it is assumed that the [former is for the `children` field](https://docs.rs/ruma/latest/ruma/api/federation/space/struct.SpaceHierarchyChildSummary.html), and the [latter is for the `room` field](https://docs.rs/ruma/latest/ruma/api/federation/space/struct.SpaceHierarchyParentSummary.html). However, in the example request in the spec, both the `children` and `room` fields use the `children_state` field, so it is unclear whether the example is correct and they should both have the `children_field`, ruma is correct and only the `room` field should have that, or even maybe the `children` field should have that and the `room` field shouldn't.
Either way, they really should either be merged (for the former solution), or have different names (for the others).

**Comment by deepbluev7** [comment]
According to the openapi spec, only `room` should have that field: https://github.com/matrix-org/matrix-spec/blob/c4e69d8cb15c3442484e988a83dc85d749423caa/data/api/server-server/space_hierarchy.yaml

**Comment by zecakeh** [comment]
It seems like the types are indeed supposed to be different:

1. [MSC2946 says](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/2946-spaces-summary.md?plain=1#L257-L258):
    > **`children_state`**: As per Client-Server API version, though only on the `room`
  and not `children`.
2. In the Synapse implementation, there is a comment that says explicitely that the `children_state` is not set on `children` items: https://github.com/element-hq/synapse/blob/274f289a52a0097784d7179c1d912dbc3cfda3ee/synapse/handlers/room_summary.py#L402-L403

**Comment by clokep** [comment]
> There are two different types with the name `PublicRoomsChunk`

There's also a third use under the [public rooms API](https://spec.matrix.org/v1.9/server-server-api/#public-room-directory), I don't know if this causes issues or not but is certainly confusing.
