### ISSUE TITLE
Inconsistent `m.call.candidates` candidate definition

### ISSUE THREAD

**Issue by stefanceriu** [matrix-org/matrix-spec#1738]
**Issue**
The spec expects [m.call.candidates](https://spec.matrix.org/v1.9/client-server-api/#mcallcandidates) events to contain an array of `Candidates`, where each one has 3 **required** fields: `candidate`, `sdpMLineIndex` and `sdpMid`

[The spec also says](https://spec.matrix.org/v1.9/client-server-api/#end-of-candidates) that end of discovery should be marked by `An ICE candidate whose value is the empty string`, which contradicts the Candidate definition.

This in turn causes problems on implementations that are strict about required fields e.g. [Ruma](https://github.com/ruma/ruma/blob/f24cae17f50d140a0ff112cb3dc74a2053aa1df4/crates/ruma-events/src/call/candidates.rs#L10-L37) which throws deserialization errors in this case.

**Expected behaviour**
The spec should be clear about what Candidates can look like. Ideally they would've been typed but I guess that ship has sailed.

**Comment by zecakeh** [comment]
This is strongly related to #1078: both can be fixed by marking `sdpMid` and `sdpMLineIndex` as optional.
