### ISSUE TITLE
Add a version picker UI to the documentation website

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/matrix-spec#1768]
If you come to the spec and don't have the latest version open, it's difficult to see which version is the latest or to switch between versions.

It would be good to have a versions picker, siliar to:
- https://github.com/matrix-org/synapse/pull/16533

**Comment by richvdh** [comment]
There was an attempt at this at https://github.com/matrix-org/matrix-spec/pull/1131, but it didn't get finished off. It might provide a useful basis if anyone wanted to pick this up again though.

**Comment by dklimpel** [comment]
This is a duplicate to
- #951
