### ISSUE TITLE
Clarify Room ID requirements

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-spec#1826]
**Link to problem area**:
https://spec.matrix.org/latest/appendices/#room-ids

**Issue**
- According to https://matrix.to/#/%23urandom%3Amaunium.net/%24GC76GPFSf0n8VEHdZN2FxSgiRb2MGDcA6L0DRwAVR7s?via=sosnowkadub.de&via=exkc.moe&via=synapse.test.progval.net&via=ucmeet-server.business.celcom.com.my Room IDs need to be limited to 255 chars to be valid in state keys
- these 255 chars probably apply to URL encoded ASCII representation because room IDs get used in URIs? I'm not sure. it seems strange that character-set, encoding, etc appears to not be defined while user IDs at least speak of UTF-8 and explicitly state a 255 char limit.

**Comment by richvdh** [comment]
Why are room IDs used in state keys?

**Comment by deepbluev7** [comment]
> Why are room IDs used in state keys?

https://spec.matrix.org/v1.10/client-server-api/#mspacechild-relationship

**Comment by HarHarLinks** [comment]
for some reason, size limits appear in this place https://spec.matrix.org/v1.10/client-server-api/#size-limits

this might answer my second question and is not referenced from the appendix section

**Comment by richvdh** [comment]
Oh, that section seems pretty clear about the requirements here.

Seems like this should be defined in the appendix, and then referenced from the "size limits" section.

PRs to update this would be very welcome.
