### ISSUE TITLE
Wrong implementation version in appservice ping endpoint

### ISSUE THREAD

**Issue by debdutdeb** [matrix-org/matrix-spec#1837]
**Link to problem area**: https://github.com/debdutdeb/matrix-spec/blob/a17550648cc4d96bf79ed21103fe30503e1a0fae/content/application-service-api.md?plain=1#L210-L212

**Issue**

Spec says endpoint was added in 1.7, in reality even the unstable proposal implementation was in 1.10 - [unstable](https://github.com/element-hq/synapse/commit/b0a0fb5c97449720c679045f1bb5a5f393b1c267), later [stable](https://github.com/element-hq/synapse/commit/86d541f37c1bc9197a6f561b31f3aa359740b4bd)

**Expected behaviour**

- mention the correct implementation version for the endpoint correctly in spec
- or backport change to 1.7

I feel like `#1` is more realistic and easier. As it hasn't been fixed, I think it's safe to assume nobody tried it on 1.7 yet, and simultaneously been so upset or blocked to the version that demanded a backport.

**Comment by tulir** [comment]
It sounds like you may have been confused by versioning of the spec? The spec does not concern itself with implementation versions, "added in v1.7" means it was added in v1.7 of the spec, hence being in the spec v1.7 changelog. You can see it being a part of the v1.7 spec here: https://spec.matrix.org/v1.7/application-service-api/#pinging (while in v1.6 it's not present: https://spec.matrix.org/v1.6/application-service-api/#pinging)

The feature was added in v1.80.0 of Synapse (and stabilized in v1.84.0), but that's not relevant for the spec.

**Comment by clokep** [comment]
Sounds like this is all set -- closing.
