### ISSUE TITLE
Order field in m.tag is a float even though Canonical JSON forbids floats

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-spec#1864]
**Link to problem area**:

https://spec.matrix.org/v1.10/client-server-api/#mtag

**Issue**

The `order` field in the content of `m.tag` is spec'ed as a number between 0 and 1. However, [Canonical JSON](https://spec.matrix.org/v1.10/appendices/#canonical-json) explicitly forbids floating point numbers.

https://github.com/matrix-org/matrix-spec/issues/615#issuecomment-1055933309 mentions "a mess with strings vs. floats in tag orders" but I couldn't find where any place that discusses this further.

**Comment by richvdh** [comment]
> The `order` field in the content of `m.tag` is spec'ed as a number between 0 and 1. However, [Canonical JSON](https://spec.matrix.org/v1.10/appendices/#canonical-json) explicitly forbids floating point numbers.

I don't think that matters? `m.tag` is account data, which is never encoded as Canonical JSON?

**Comment by Johennes** [comment]
Err, yes you're right. My bad, apologies. 🤦
