### ISSUE TITLE
Broken templates on the swagger playground

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-spec#1894]
**Link to problem area**:
e.g.
https://playground.matrix.org/#get-/_matrix/client/v1/media/thumbnail/-serverName-/-mediaId-

at least the 3 download endpoints are affected

**Issue**
![image](https://github.com/matrix-org/matrix-spec/assets/2803622/c0a231bf-e0f3-4b07-b475-41f34d481429)
`{{% boxes/note %}}`

**Comment by KitsuneRal** [comment]
Already reported as https://github.com/matrix-org/matrix-spec/issues/1873
