### ISSUE TITLE
Fallback login spec doesn't specify what arguments `onLogin` takes (if any)

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-spec#1900]
**Link to problem area**:

https://spec.matrix.org/v1.11/client-server-api/#login-fallback

**Issue**

The fallback login specification mentions a function that is called when login is completed.

> The page will attempt to call the JavaScript function `window.onLogin` when login has been successfully completed.

It does, however, not specify what parameters the function is called with, if any.

Synapse appears to [pass in](https://github.com/matrix-org/synapse/blob/236d2d699d48e15d3c16ebd82dc8473a2fff8aca/synapse/static/client/login/js/login.js#L42) the response body of the `POST /login` request parsed from JSON into a JavaScript object by [jQuery](https://api.jquery.com/jQuery.post/).

```
$.post(matrixLogin.endpoint, JSON.stringify(data), function(response) {
    ...
    matrixLogin.onLogin(response);
})
```

Dendrite has [copied](https://github.com/matrix-org/dendrite/commit/bebf701dce01d47264d694b118c81dcb84a37b04#diff-b72a6ec1a210d8e4c9e7a2c750fa8d93477b1222d7b2cc3ee87248ab31fbc626R42) Synapse's behavior.

On the client-side, element-ios, for instance, depends on this behavior and [parses](https://github.com/element-hq/element-ios/blob/bec5ed590d0330e3932df3ad110fc92ea72b84df/Riot/Modules/Home/Fallback/AuthFallBackViewController.m#L193) the passed argument to a login response.

Similar to the argument made in https://github.com/matrix-org/matrix-spec/issues/640#issuecomment-2209163225, I suspect this is simply a spec omission that we can fix without an MSC?

**Comment by clokep** [comment]
I think if that is what synapse has always done since implementing this then we can just clarify the spec.
