### ISSUE TITLE
GET /.well-known/matrix/client only allows additional properties of type `object`

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-spec#1913]
**Link to problem area**:

https://spec.matrix.org/v1.11/client-server-api/#getwell-knownmatrixclient

https://github.com/matrix-org/matrix-spec/blob/d9c447e194180df5efa75ab25803d317d7df5f7f/data/api/client-server/definitions/wellknown/full.yaml#L25

**Issue**

The spec currently allows additional properties of type `object` in the response of `GET /.well-known/matrix/client`. It's unclear whether this actually intended to restrict values to JSON objects or not.

I cannot think of a reason why only objects should be allowed and FWIW [MSC4158](https://github.com/matrix-org/matrix-spec-proposals/pull/4158) attempts to introduce a property `m.rtc_foci`of type `array`.

**Comment by Johennes** [comment]
As further evidence Synapse's `extra_well_known_client_content` config setting allows specifying additional keys with values of arbitrary type: https://github.com/element-hq/synapse/blob/develop/synapse/rest/well_known.py#L63-L69

**Comment by richvdh** [comment]
I'm pretty sure this was just a mistake by whoever wrote that openapi doc.

**Comment by turt2live** [comment]
for links, the original proposal is https://github.com/matrix-org/matrix-spec-proposals/issues/433 and specified by https://github.com/matrix-org/matrix-spec-proposals/pull/1359

The proposal doesn't forbid non-object values, and appears to imply support for whatever people want:
![image](https://github.com/user-attachments/assets/f073f697-b476-44ad-9bd4-9b299aaa0f00)

(in case we needed documentation that this doesn't require an MSC)
