### ISSUE TITLE
Text calling

### ISSUE THREAD

**Issue by Feliks-WR** [matrix-org/matrix-spec#1925]
In addition to voice and video calling, it would be very useful to have text calling, in which one could see what the others are typing, *in real time*.

It should use the same protocol(s) as voice/video calling, but should instead transfer text, rather than voice.

This would be a groundbreaking feature, and would close the gap between simple messaging and voice calling.

**Comment by Feliks-WR** [comment]
It would be genuinely useful!
Atleast make an integration for it???

**Comment by richvdh** [comment]
Features like this are normally developed and standardised by a specific client implementation.

I'd suggest persuading a specific client implementation that it should be added, rather than attempting to push it through the spec without an implementation.

**Comment by Feliks-WR** [comment]
> Features like this are normally developed and standardised by a specific client implementation.
> 
> I'd suggest persuading a specific client implementation that it should be added, rather than attempting to push it through the spec without an implementation.

Would it not require server side support??
