### ISSUE TITLE
Restricting permissions for relations - Thread-only rooms

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix-spec#1931]
**Suggestion**

## Stage 1 Wish

Allowing to restrict the ability to do replies in a room forcing users to use threads

## Stage 2 Wish

Restricting replies in the main timeline but allowing it inside of threads to be used

## Stage 3 Wish

Powerlevel support for arbitrary relations.

**Background**

Rooms like TWIM (sadly) are prone to heavy and long offtopic discussions. It would be amazing to force people into thread usage to avoid main-timeline noise significantly.

**Comment by MTRNord** [comment]
Related: https://github.com/matrix-org/matrix-spec/issues/836

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/matrix-spec/issues/836
