### ISSUE TITLE
Room: Mount Remote Cloud Storage

### ISSUE THREAD

**Issue by ghost** [matrix-org/matrix-spec#1942]
# suggestion
I don't want to run my own Matrix server.

I want to run my own matrix media storage.

I have my own cloud storage, NSA Storage/SAN, and Storage/MinIO.

I just need to add WebDav to the Matrix room I created,
so that all uploaded large files will be stored in WebDav. and not on matrix.org

---
---

## From GPT explanation

To set up your own media storage for Matrix using WebDAV without running your own Matrix server, you can follow these steps:

### 1. Set Up WebDAV

Ensure that your cloud storage solution (NSA Storage/SAN or MinIO) has WebDAV support enabled. If you're using MinIO, you may need to set up a WebDAV-compatible service or use a proxy that allows WebDAV access.

### 2. Use a Matrix Client with WebDAV Support

You will need a Matrix client that allows you to configure external storage options. Some clients may have built-in support for WebDAV, while others may require additional configuration or plugins.

### 3. Configure WebDAV in Your Matrix Client

If your Matrix client supports it, configure the WebDAV settings to point to your WebDAV server. This typically involves:

- **WebDAV URL**: Set the URL to your WebDAV server (e.g., `https://your-webdav-server/path`).
- **Authentication**: Provide any necessary authentication details (username and password).

### 4. Create a Matrix Room

If you haven't already, create a Matrix room where you want to store files. You can do this using your Matrix client.

### 5. Upload Files to the Room

When you upload files to the Matrix room, ensure that the client is configured to use WebDAV for file storage. Depending on the client, this may happen automatically, or you may need to select the WebDAV option when uploading files.

### 6. Verify File Storage

After uploading files, check your WebDAV server to ensure that the files are being stored there instead of on the Matrix.org servers. You can do this by accessing the WebDAV directory and confirming the presence of the uploaded files.

### Additional Considerations

- **Permissions**: Ensure that the permissions on your WebDAV server are set correctly to allow uploads from your Matrix client.
- **Security**: Use HTTPS for your WebDAV server to secure the data in transit.
- **Backup**: Regularly back up your WebDAV storage to prevent data loss.

By following these steps, you should be able to set up a Matrix room that uses WebDAV for file storage without needing to run your own Matrix server. If you encounter specific issues or need further assistance with a particular client or setup, feel free to ask!

**Comment by KitsuneRal** [comment]
The configuration of the matrix.org homeserver is not meant for individual tweaking. Rooms in Matrix are decentralised, they do not belong to any specific homeserver. When uploaded, it is the homeserver of each user deciding where the files end up being stored; other homeservers can cache these files. So I am not sure what you exactly mean by "add WebDav to the room". Do you want to write or to read the files over WebDAV?
