### ISSUE TITLE
Stop using canonifyURLs

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-spec#1957]
As reported by @zecakeh in https://github.com/matrix-org/matrix-spec/pull/1937#issuecomment-2383089818, the `canonifyURLs: true` setting appears to be deprecated and causes issues when used together with `--baseURL`. We should probably work on removing `canonifyURLs`.

**Comment by zecakeh** [comment]
I have managed to do that locally but we need changes to our fork of docsy, see https://github.com/matrix-org/docsy/pull/3#issuecomment-2383886235.
