### ISSUE TITLE
Matrix Reference Implementation

### ISSUE THREAD

**Issue by Maniues** [matrix-org/matrix-spec#1962]
**Link to problem area**:
Current Matrix Specification states that Matrix is fully open:
```
Fully open:

    Fully open federation - anyone should be able to participate in the global Matrix network
    Fully open standard - publicly documented standard with no IP or patent licensing encumbrances
    **Fully open source reference implementation - liberally-licensed example implementations with no IP or patent licensing encumbrances**
```
**Issue**
After Element's fork of Synapse, Matrix has **no reference implementation**, at least it is not liberally licensed.
If the Matrix Foundation does not maintain any reference implementation, the specification should not reflect this. 

Worse, if there is no implementation that could be fully compliant with the specification, stable and openly managed, I do not know if then it is possible to call Matrix fully open in the sense of the current specification and the Matrix Foundation position.

**Comment by clokep** [comment]
> **Link to problem area**:
> Current Matrix Specification states that Matrix is fully open:

The link is https://spec.matrix.org/latest/#introduction-to-the-matrix-apis

> After Element's fork of Synapse, Matrix has **no reference implementation**, at least it is not liberally licensed.

Synapse has not considered itself a reference implementation for several years (long before the fork by Element). (This likely doesn't change your concern.)

**Comment by richvdh** [comment]
Indeed; cf https://github.com/matrix-org/synapse/pull/10971.

We should just remove this mention of "reference implementation" from the spec.

**Comment by richvdh** [comment]
I did, but I don't have a good answer for you. It just doesn't? Nobody has found it a worthwhile way to spend their time.
