### ISSUE TITLE
Swagger Viewer points to 404

### ISSUE THREAD

**Issue by jo-so** [matrix-org/matrix-spec#2]
**Link to problem area**: <https://spec.matrix.org/latest/#matrix-apis>

**Issue**

The link on »The Matrix Client-Server API Swagger Viewer is useful for browsing the Client-Server API.« points to <https://matrix.org/docs/api/client-server/>, but this gives an »404 Not Found«.

**Expected behaviour**

Either remove the link or point to where the resource is.

**Comment by afranke** [comment]
Technically, this could be closed, as the redirect is indeed already in place. However, I went ahead and submitted a PR that also fixes the link to the new location.
