### ISSUE TITLE
Should we prepend anti-eval code to our json responses?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-spec#244]
Google and FB prepend while(1); or for(;;) or similar to the beginning of all their JSON responses to force malicious clients to not be able to `eval` the responses when stealing data (eg after overriding core bits of JS like Array). Should we too?

**Comment by richvdh** [comment]
5.5 years later, I'm still failing to grok the attack, and nobody seems that bothered about it. I'm closing this.
