### ISSUE TITLE
Allowing application services to deny a join

### ISSUE THREAD

**Issue by Ekleog** [matrix-org/matrix-spec#272]
I was reading the application service spec, and read “Rooms which are publicly accessible (e.g. IRC rooms) can be exposed as an alias by the application service. Private rooms (e.g. sending an email to someone) should not be exposed in this way, but should instead operate using normal invite/join semantics.”

This made me think about the matrix-appservice-irc, that actually exposes private (ie. invite-only) IRC rooms as rooms with an alias. This is likely the easiest user interface, but security implications look problematic to me: it means the application service must support the bridged protocol perfectly, so that it does not miss a case where the matrix-side room should be invite-only.

Also, I think it means that currently if a matrix user is banned IRC-side, if they try to join the channel via the bridge, they will be let in the room before being kicked by the appservice. Which in turn means that this user's homeserver will be allowed to synchronize the history, which could lead to information disclosure if this rogue user controls their own homeserver and can just read the contents of the room in the database after having been kicked.

So I was thinking maybe it would be a better interface for the appservice to, rather than rely on “normal” matrix rooms, be able to specify that the appservice should be called back into when a user wants to join, so the appservice can deny the join request without having to map it exactly into matrix-side permissions (because sometimes the models just vary enough that it's much easier to do it this way).

The realization of this idea would basically be the addition of an endpoint in the appservice API, similar to (I'm not really knowledgeable about the conventions of the matrix API, just giving ideas):
```
GET /rooms/{roomId}/join?user_id={userId}

200 => {userId} is allowed to join
401,403,404 => see GET /rooms/{roomAlias}
409 => {userId} is not allowed to join
```
Unresolved questions:
 * I guess 403 would be better than 409, but it's already taken, so disambiguation would be harder, and I couldn't find a better standard response code -- so maybe switch to a non-standard one?
 * `roomId` or `roomAlias`? `roomId` is more straightforward for the HS, while `roomAlias` is simpler for the AS. I think `roomId` is better because an AS could decide to give multiple aliases to the same room, but this may be a debatable statement?

There is also the question of “muted” channels on IRC (mode +m usually), that could make it better to have a similar potentially-blocking-the-operation hook for sending events to a room.

Obviously, such a callback would be called only when the appservice has exclusive access to a room, because otherwise things will very quickly become a mess.

**Comment by turt2live** [comment]
from oob conversations, it sounds like this would be solved via knocking at the moment. Some of the antispam characteristics might be solved in other ways still, but for this particular issue the appservice can set up the room as knocking-only and deny joins that way.

This assumes appropriate client support, which should be reasonable given the current age of the feature in the spec.
