### ISSUE TITLE
/createRoom initial_state possibly incorrectly allows state_key to be omitted

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-spec#309]
More of a potential spec bug, but in [/createRoom](https://spec.matrix.org/v1.6/client-server-api/#post_matrixclientv3createroom) we describe ``state_key`` as being optional and if omitted, it should be empty string. This might not be the best approach and in the future we should require it (this came up in matrix-org/matrix-spec-proposals#1329).

**Comment by richvdh** [comment]
For the record, this is referring to this:

![image](https://user-images.githubusercontent.com/1389908/227168494-0f48d9a4-6222-4d53-ab3c-aefb4d89f146.png)

I'm going to close this as a WONTFIX. If someone wants to make an MSC proposing to mandate `state_key` I won't stop them, but I don't see it as a priority.
