### ISSUE TITLE
Sometimes the generator flips the order of parameters

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#336]
Expected (path first):
![image](https://user-images.githubusercontent.com/1190097/43622606-3af6b238-969a-11e8-8e9f-3bd11104d1f2.png)

Sometimes (body first):
![image](https://user-images.githubusercontent.com/1190097/43622612-427ceff4-969a-11e8-883f-95370fad65ed.png)

**Comment by zecakeh** [comment]
I must say I haven't seen that recently and given the current code, I don't see how that would be possible.
