### ISSUE TITLE
3pid lookup types in the Identity Server spec are unclear

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#358]
It renders as `[string, string, string]` which is entirely unhelpful. OpenAPI really hates us using our own types though, hence https://github.com/matrix-org/matrix-doc/commit/684d80c4228f87b0268581f3f52660e8fbbbb165

**Comment by zecakeh** [comment]
This seems to be for the `/bulk_lookup` endpoint from the identity service API that was deprecated in Identity Service API r.0.3.0 and removed in Matrix 1.1.
