### ISSUE TITLE
Spec how N+1 replies work in terms of fallback

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#372]

**Comment by Cadair** [comment]
Am I correct in thinking that the way these work is that you just fall back to the most recent message you are replying to?

**Comment by richvdh** [comment]
I don't even know what N+1 replies are

**Comment by Cadair** [comment]
I was assuming it was talking about replies to replies (to replies (...))

**Comment by turt2live** [comment]
Yea, this is replies to replies [to replies [...]]. 

The question is mostly what you're supposed to stick in the `<mx-reply>` (and markdown-ish quote block): some clients believe the whole chain should be there, but others disagree. We mostly just need to pick something that makes sense and do that.

It's possible this needs an MSC.

**Comment by Cadair** [comment]
Given the open MSCs about ripping out the fallbacks completely I think I will leave this one to be overtaken by events...
