### ISSUE TITLE
Future Proposal for Cryptographic Challenge Login Flow and E2E Key Backup Recovery

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-spec#388]
Documentation: https://docs.google.com/document/d/1QXMJmLiRWQxZOlynVVk99KhumlM7-7bTrGatBG0AQfU/edit#heading=h.apnhwogtw3jb

I'm recording this as a (very rough and ready, and not yet markdown) MSC in order to capture it, even though the conclusion is consciously to postpone it until a later date.

**Comment by richvdh** [comment]
I think this has been superceded by MSC2957, MSC3262 and MSC3265.
