### ISSUE TITLE
Group admin promotion

### ISSUE THREAD

**Issue by krombel** [matrix-org/matrix-spec#393]
Request: Add a way to promote a user as admin.

The current spec proposals e.g. mentioned in matrix-org/matrix-spec-proposals#971 do not cover a way to add or remove admins for a group. It is currently possible with database fiddling but there should be an official way via API.

This is related to https://github.com/matrix-org/synapse/issues/2855

**Comment by aaronraimist** [comment]
This can probably be closed since groups were never specced and have been replaced with spaces.
