### ISSUE TITLE
s2s spec: matrix service name already reserved by other usage according to IANA registry

### ISSUE THREAD

**Issue by norwoman** [matrix-org/matrix-spec#400]
Section 2.1 of server-to-server API describes the usage of a `_matrix._tcp` SRV record to discover the service hostname and port. However the `matrix` service name is already registered for use with the `MATRIX Remote AV Switching` protocol, as per the [Service Name and Transport Protocol Port Number Registry](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml) of IANA.

To avoid conflicts with existing infrastructure, Matrix s2s should use a different service name, examples could be `matrix-server` or `matrix-org`. Also, please make sure to [register the new service name](https://www.iana.org/form/ports-services) with the registry to avoid future conflicts.

**Comment by turt2live** [comment]
our new service name is `matrix-fed` - to be turned into an MSC.

Port 8448 is registered under https://github.com/matrix-org/matrix-spec/issues/1576

**Comment by turt2live** [comment]
MSC to fix the SRV record lookup: https://github.com/matrix-org/matrix-spec-proposals/pull/4040
