### ISSUE TITLE
Outdated "public_keys" section in response for /store-invite in the IS spec

### ISSUE THREAD

**Issue by babolivier** [matrix-org/matrix-spec#495]
Since https://github.com/matrix-org/sydent/pull/13, Sydent changed the responses it returns on `/store-invite` requests from

```json
{
  "token": "sometoken",
  "public_keys": [
    "serverpublickey",
    "ephemeralpublickey"
  ],
  "display_name": "f...@b..."
}
```

to

```json
{
  "token": "sometoken",
  "public_key": "serverpublickey",
  "public_keys": [
    {
      "public_key": "serverpublickey",
      "key_validity_url": "https://vector.im/_matrix/identity/api/v1/pubkey/isvalid"
    },
    {
      "public_key": "ephemeralpublickey",
      "key_validity_url": "https://vector.im/_matrix/identity/api/v1/pubkey/ephemeral/isvalid"
    },
  ],
  "display_name": "f...@b..."
}
```

Currently, the spec documents the former (and outdated) format: https://matrix.org/docs/spec/identity_service/latest#post-matrix-identity-api-v1-store-invite

**Comment by richvdh** [comment]
Fixed in #1486. Have filed https://github.com/matrix-org/sydent/issues/561 to remove the unspecced `public_key` param in sydent.
