### ISSUE TITLE
room_id and servers are required on the response of GET /directory/:alias

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#497]
https://matrix.to/#/!jxlRxnrZCsjpjDubDX:matrix.org/$en1XoW37miNZeTJ1kt9JTLnRt-3Mqn-QxD5d23OftyM?via=matrix.org&via=t2l.io&via=encom.eu.org

**Comment by richvdh** [comment]
Unfortunately the context here has ben lost to time, so I'm going to close it. If anyone knows what it was, and it still seems relevant, we can reopen.
