### ISSUE TITLE
Weird spaces after dashes in inline code blocks is still present

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#499]
https://i.imgur.com/2wdhIuY.png / https://matrix.org/docs/spec/identity_service/r0.2.1#post-matrix-identity-api-v1-sign-ed25519

**Comment by zecakeh** [comment]
The endpoint is this one now: https://spec.matrix.org/v1.10/identity-service-api/#post_matrixidentityv2sign-ed25519.

According to the image, the problem was with `store-invite`, but I don't see any problem anymore.

**Comment by richvdh** [comment]
Agreed, let's close. Thanks!
