### ISSUE TITLE
Add server_acl to checks on PDU arrival

### ISSUE THREAD

**Issue by lucavb** [matrix-org/matrix-spec#526]
The Server-Server API defines the steps a homeserver needs to perform before a event is accepted under [6.1](https://matrix.org/docs/spec/server_server/r0.1.3#checks-performed-on-receipt-of-a-pdu). The Client-Server API specifies at the same time in the note under [13.29.1](https://matrix.org/docs/spec/client_server/latest#id638) for `m.room.server_acl` that the server_acl needs to prevent communication on a network layer based on these server acls. The section in the Server-Server API makes no mention of these server acls.

It is probably a good idea to reference the server acls within the Server-Server API as well and specify at what step this is supposed to be performed.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/matrix-spec/issues/928
