### ISSUE TITLE
POST /keys/upload schema and example don't match.

### ISSUE THREAD

**Issue by Dominaezzz** [matrix-org/matrix-spec#530]
So for this property, https://github.com/matrix-org/matrix-doc/blob/03641d9e48c3e3e73ff8b3c851e2338fb8ceea87/api/client-server/keys.yaml#L75-L80

One of the examples are,
https://github.com/matrix-org/matrix-doc/blob/03641d9e48c3e3e73ff8b3c851e2338fb8ceea87/api/client-server/keys.yaml#L86-L90

The schema and example doesn't match so one of them is wrong. (The doc seems to insist the example is wrong).

TL;DR
The schema says, `Map<String, String>` but the example is `Map<String, Map<String, String>>`.

**Comment by zecakeh** [comment]
This is fixed now: the [example](https://github.com/matrix-org/matrix-spec/blob/e15a36b0a1e69d40ffe1a1ebcdc5666b3a7236f0/data/api/client-server/keys.yaml#L52-L62) matches [the schema](https://github.com/matrix-org/matrix-spec/blob/main/data/api/client-server/definitions/one_time_keys.yaml). `signatures` is declared as a `Map<String, Map<String, *>>`.

We even have a script in CI that ensure that examples match the schemas.
