### ISSUE TITLE
Consider replacing `m.room.aliases` with an `m.room.alias` event listing a single alias

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-spec#532]
Currently, the `m.room.aliases` state event has a state_key corresponding to a given server name, and it lists all the aliases for a given room on that server (or at least, it is intended to). This runs the risk of races when making several changes to the directory at once. 

Instead, we could have an `m.room.alias` event for each alias. For example:

```json
{
    "sender": "@user:foo.com",
    "type": "m.room.alias",
    "state_key": "#sommeliers:foo.com",
    "content": {}
}
```

(This was originally proposed in matrix-org/matrix-spec-proposals#1130, but I have split it to here to remove redundant content.)

**Comment by KitsuneRal** [comment]
`m.room.aliases` is no more a thing, and we took a different route about the whole thing instead of introducing `m.room.alias`. Should this be closed-as-not-planned?

**Comment by richvdh** [comment]
Indeed. MSC2432 removed the special meaning for `m.room.aliases`.
