### ISSUE TITLE
Clarify what query parameters mean in thirdparty endpoints

### ISSUE THREAD

**Issue by wfdewith** [matrix-org/matrix-spec#560]
The [`/_matrix/client/r0/thirdparty/location/{protocol}`](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-thirdparty-location-protocol) endpoint specifies a `searchFields` query parameter with type `string`, but the description mentions it's: "one or more". What is the actual format for this query parameter?

The same is also true for [`/_matrix/client/r0/thirdparty/user/{protocol}`](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-thirdparty-user-protocol), the only difference being that the query parameter is called `fields...`. I found in [`api/openapi_extensions.md`](https://github.com/matrix-org/matrix-doc/blob/master/api/openapi_extensions.md) that it is supposed to mean "one or more", but no specification on the actual format.

**Comment by deepbluev7** [comment]
The openapi spec should now be correct with https://github.com/matrix-org/matrix-spec/commit/14051847653383e432ebacae2cc430cc9ebce1e0 and https://github.com/matrix-org/matrix-spec/pull/1947. The text/rendering of the spec might still be unclear though.

For me it wasn't immediately obvious why that is the case though, so let me explain (for future me for example):
- The query parameters are now objects (of string: string)
- The query parameters use the default style: form
- In that case the explode option defaults to true, which expands the object into separate query parameters

References:
- https://swagger.io/docs/specification/describing-parameters/#query-parameters
- https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-10

**Comment by richvdh** [comment]
Since things have changed a bit since this issue was opened, I've opened a new one to summarise the situation: https://github.com/matrix-org/matrix-spec/issues/1993.
