### ISSUE TITLE
Typing CS documentation contains mistake about the room_id

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-spec#578]
In https://matrix.org/docs/spec/client_server/latest#id49, the part:

> but still have a room_id key

is not correct.

Also in the sample of https://matrix.org/docs/spec/client_server/latest#m-typing:

```json
{
    "content": {
        "user_ids": [
            "@alice:matrix.org",
            "@bob:example.com"
        ]
    },
    "room_id": "!jEsUZKDJdhlrceRyVU:example.org",
    "type": "m.typing"
}
```

contains `room_id` field, which is actually not the case.

The typing event is already in the rooms.join.{room_id}.ephemeral.events list of the sync response, so `room_id` is not necessary in the event content. And it's actually not there. The issue is just in the documentation.

**Comment by richvdh** [comment]
in https://spec.matrix.org/v1.3/client-server-api/#typing-notifications, looks like the example has been updated but not the text.
