### ISSUE TITLE
Modern encryption

### ISSUE THREAD

**Issue by sylvain1010** [matrix-org/matrix-spec#597]
Hi,
I couldn't find an issue about this, so I open this one.

OLM and MegOLM use old cipher like `AES-256-CBC`, `HMAC-SHA-256 ` which have a lot of drawbacks (like hard to review, vulnerable to hardware backdoors...).

Is there any plan to use modern ciphers instead, like `XChaCha20-Poly1305`, `blake2b` and so on?

**Comment by richvdh** [comment]
I'm going to go ahead and close this; as @uhoreg says, we have no immediate plans to change to change the ciphers used in olm and megolm.

Related issues include: https://github.com/matrix-org/matrix-spec/issues/1557, https://github.com/matrix-org/matrix-spec/issues/975, https://github.com/matrix-org/matrix-spec/issues/934.
