### ISSUE TITLE
Need a way to paginate forwards from the start of a room's timeline

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-spec#601]
Sometimes paginating forwards from the very start of a room is a useful thing to do. It's possible if you have the event id of the create event, but otherwise is tricky.

**Comment by MadLittleMods** [comment]
As a cumbersome workaround, we can use [MSC3030](https://github.com/matrix-org/matrix-spec-proposals/pull/3030) to jump to the first event in the room:

 1. `GET /_matrix/client/v1/rooms/<roomID>/timestamp_to_event?ts=0&dir=f` to get the first event in the room
 2. `GET /_matrix/client/r0/rooms/<roomId>/context/<eventId>?limit=0` to get a pagination token
 3. Use `/messages?dir=f` to paginate forwards

**Comment by richvdh** [comment]
I think MSC3567 solves this?

**Comment by MadLittleMods** [comment]
`GET /_matrix/client/v3/rooms/{roomId}/messages?dir=f` doesn't seem to work to get the first messages in the room as [MSC3567](https://github.com/matrix-org/matrix-spec-proposals/issues/3567) mentions ❌

```
{
    "chunk": [],
    "start": "s957_0_0_0_0_0_0_0_0",
    "end": "s957_0_0_0_0_0_0_0_0"
}
```

`GET /_matrix/client/v3/rooms/{roomId}/messages?dir=b` does get the latest events in the room as [MSC3567](https://github.com/matrix-org/matrix-spec-proposals/issues/3567) mentions though.

**Comment by richvdh** [comment]
> `GET /_matrix/client/v3/rooms/{roomId}/messages?dir=f` doesn't seem to work to get the first messages in the room as [MSC3567](https://github.com/matrix-org/matrix-spec-proposals/issues/3567) mentions x.

That sounds like a synapse bug rather than a spec one, tbh.

(though it does make me wonder: what happens if the local server doesn't have the start of the room history?)

**Comment by MadLittleMods** [comment]
> (though it does make me wonder: what happens if the local server doesn't have the start of the room history?)

👍 Can't backfill forwards. It's weird.

**Comment by richvdh** [comment]
ok, so it seems like we can close this? The spec at least has a way to do this. @MadLittleMods: if you find synapse doesn't implement it correctly, please can you file a bug over there.
