### ISSUE TITLE
Federation API spec does not declare fields as required for /_matrix/key/v2/server

### ISSUE THREAD

**Issue by valkum** [matrix-org/matrix-spec#613]
in https://matrix.org/docs/spec/server_server/r0.1.3#get-matrix-key-v2-server-keyid does not declare the response fields as required but synapse fails with a KeyError when at least on of the fields is not present.

**Comment by HPOA909** [comment]
I have this problem, too; when the federation tester is constantly searches through my server for that specific key file.
