### ISSUE TITLE
Login with QR code AND cross-signing in one shot 

### ISSUE THREAD

**Issue by cyanlemons** [matrix-org/matrix-spec#627]
We currently have QR code cross-signing. You will typically perform the cross-signing immediately after you login on a new device.

Discord currently allows users to login with QR codes if they are already logged in on another device.

It seems like the obvious next step in terms of better UX is to kill two birds with one stone. I suggest that there be an option to login and cross-sign a new device simultaneously with one QR code.

In 99% of cases wherein you are verifying a new device, you will have just recently logged in anyway, so why not make it simpler & quicker?

**Comment by eickeh** [comment]
Is that still in the pipeline? I'd love to see this feature. It would especially make it easier to login with the App in a single sign on environment with a 2nd factor enforced.

**Comment by uhoreg** [comment]
It's being investigated, but I don't think there's a timeline available yet.

**Comment by ara4n** [comment]
MSC4108 provides this, and it works.
