### ISSUE TITLE
Replace "OpenMarket Ltd" with "The Matrix.org Foundation C.I.C." in copyright notices

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#634]
https://github.com/matrix-org/synapse/issues/7565#issuecomment-639171606

**Comment by Aman-Sigroha** [comment]
I have sent a pull request after  replacing  "OpenMarket Ltd" with "The Matrix.org Foundation C.I.C."

**Comment by tulir** [comment]
https://github.com/matrix-org/synapse/issues/7565#issuecomment-1410216403 indicates we want to leave the notices alone after all
