### ISSUE TITLE
properly remove per-device push rules

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-spec#637]
the APIs are still hanging around, which confuses people. we should add them back to the spec deliberately in future

**Comment by richvdh** [comment]
I've opened https://github.com/matrix-org/synapse/issues/12482 to track updating the Synapse API. 

As it concerns the spec, device scopes are mentioned in a couple of places: https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3pushrulesscopekindruleidactions and https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3pushrulesscopekindruleidenabled, which both say "`scope`: **Required**: Either `global` or `device/<profile_tag>` to specify global rules or device rules for the given `profile_tag`."

**Comment by frederikb96** [comment]
Do I understand correctly, that the per device push rules are going to be removed and that there will be no way to have different notification profiles for different devices?

**Comment by richvdh** [comment]
Per-device push rules have never been supported. There have been some ideas for supporting per-device notification profiles in Matrix, but it won't be based on push rules.
