### ISSUE TITLE
Identity Server Domain Signature type name mismatch

### ISSUE THREAD

**Issue by iinuwa** [matrix-org/matrix-spec#652]
The `signatures` field has the type `Identity Server Signature`, but the  referenced type name is called `Identity Server Domain Signature`. One of them needs to be renamed.

**Comment by jplatte** [comment]
This seems to be what the issue is talking about, but it looks pretty clear now.

![Screenshot_2023-04-27_104648](https://user-images.githubusercontent.com/951129/234809878-27418f02-73f7-4730-a679-77909c41ecb7.png)
