### ISSUE TITLE
Login/register endpoints say the device_id and stuff aren't required in the response

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#676]
This is very much wrong

**Comment by anoadragon453** [comment]
> Same for register endpoint.

For `/register`, the spec currently says that `device_id` and `access_token` are only required if `inhibit_login` in the request is false. Synapse also [follows this advice](https://github.com/matrix-org/synapse/blob/d6e94ad9d9b22efe0f5eb64d946c10a542068f7c/synapse/rest/client/register.py#L803-L820).
