### ISSUE TITLE
Application service API authentication requires `access_token` to be in the query parameters

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-spec#679]
There's an existing issue about this at matrix-org/matrix-spec-proposals#1424, but it got closed by matrix-org/matrix-spec-proposals#1534 which updates the wording about the usage of the client-server API for appservices, but not the wording about authentication in the appservice API itself. This seems like an oversight.

**Comment by Half-Shot** [comment]
This seems like it would be solved by https://github.com/matrix-org/matrix-spec-proposals/pull/2832.

**Comment by turt2live** [comment]
Closing in favour of MSC, given it's on the edge of FCP.
