### ISSUE TITLE
Lazy-loading has a MAY keyword

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#682]
this isn't a keyword we use

**Comment by richvdh** [comment]
> this isn't a keyword we use

I kinda wish we wrote down which of the RFC2119 keywords we use and don't use. 

Anyway, this seems to refer to https://spec.matrix.org/v1.10/client-server-api/#lazy-loading-room-members:

> the server MAY assume that clients will remember membership events they have already been sent

... so should this just be "may" rather than MAY?

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/matrix-spec/issues/701

**Comment by turt2live** [comment]
historically we've avoided `may` and `MAY` due to confusing definitions in English, but if we adopt RFC 2119 then I think that's fine.

I don't believe we need an MSC to use RFC 2119 - we can just do that.

**Comment by richvdh** [comment]
Ok, so shall we just close this then?

**Comment by turt2live** [comment]
yes, closing in favour of https://github.com/matrix-org/matrix-spec/issues/1782
