### ISSUE TITLE
Sample events for reproducible and replayable VoIP over Matrix

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/matrix-spec#715]
**Is your feature request related to a problem? Please describe.**
Matrix currently does not support voice and video and we have to resort to third party apps such as Mumble, Jitsi and BBB.

**Describe the solution you'd like**
Timestamped sample events would be transmitted in the same manner as text chat. Sample events will be binary packets. Each sample event will have a header and a payload. The header will have a self-declared originator timestamp, codec info and length in terms of samples. I recommend encapsulating 500sym/event for lossless (16bit/sample assumed) and 4096bit/event for lossy codecs per sample event. A voice call will be established using sample events from multiple parties and those sample events will be assembled in the receiving end into sample mixes. Sample events may arrive out of order but will always be played in order. Sample events will have a latency negotiation, similar to shortest path establishment used in packet switching. The latency negotiation algorithm will establish that everyone hears the particular sample of a particular sample event at the same time in a reproducible manner. Extra latencies will be established not by resampling but by lengthening the pauses. Latencies will be dropped in the same manner by shortening/dropping the pauses.

**Additional context**
https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$jSgxjUJ_wyFmJ1Ia4GhEEKpiIJhKGuaeLnKdRPVuQKU
https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$HkwfL_kaf6pyimY0TA9saaM2Fvnp0tCfUvAuwAfDM7g

The relevant MSC: matrix-org/matrix-spec-proposals#3052

**Comment by turt2live** [comment]
I have general concerns that this adds too much overhead to a feature that doesn't need that overhead. I'm happy to be proven wrong with an MSC from someone, however in this issue's current state it appears to want to run WebRTC itself over Matrix instead of making the signaling work over Matrix (which is how we support VoIP currently). 

Replayability is an audio file upload, optionally as a voice message.
