### ISSUE TITLE
.well-known everywhere

### ISSUE THREAD

**Issue by notramo** [matrix-org/matrix-spec#719]
Currently, Element doesn't do .well-known verification in every case, because the spec doesn't mandates.
**As an user, I don't wan't to think about where my server is located actually.** I just want to use the address that is in my Matrix ID, after the : character. Just like with e-mail, if my address ends with `@tutanota.com`, then I say to register at tutanota.com to someone when I recommend secure e-mail to them, and if ends with `@protonmail.com`, then I say register at protonmail.com.
The downsides of having the user think about the actual address of the server:
- they may don't know it, and there is no way to guess it from the second part of the Matrix ID without knowing the path of .well-known - not noob friendly
- they may use the actual address in their Matrix ID
- **Why should they think about it, when it is easy to do it in the app automatically?** (The functions already exist in many app, they should simply call them at other places too.)

Element Android does .well-known discovery even in the server selection screen, which is not spec compliant, but it provides a lot bettex UX. (Tested it with numerous users.)

**Comment by aaronraimist** [comment]
Related/dup: https://github.com/matrix-org/matrix-spec/issues/420
