### ISSUE TITLE
Ability to mint access_tokens with restricted scope.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-spec#725]
There are many scenarios where it'd be useful to be able to give a client or AS or bot or widget or some other service limited access to your account:
 * To limit access to other APIs (e.g. to forbid an untrusted client from being able to read account_data, or to read your 3PID bindings, or attempt E2EE etc).
 * To hand access to a subset of rooms to a limited account (e.g. a read-only HUD)
 * To allow a double-puppetted bridge to send messages as your real user, but only in bridged rooms

In the past this has got a bit derailed by the idea of replacing our auth system entirely by OAuth2: https://github.com/matrix-org/matrix-doc/issues/2615 - and meanwhile an MSC trying to do something very similar to this got abandoned: https://github.com/matrix-org/matrix-doc/issues/531.  So I'm reopening this as a high level issue for folks to upvote and coordinate via.

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-spec-proposals/pull/2967 currently has the best chance of being approved, and if not it's a thing we want to do anyways. Let's triage this through the proposals process rather than as an idea, now that we have an MSC to link to.
