### ISSUE TITLE
Rooms as VoIP/Rooms as Video

### ISSUE THREAD

**Issue by InfiniteWorldSoftware** [matrix-org/matrix-spec#730]
**Is your feature request related to a problem? Please describe.**
A friend complained about a lack of a Discord-like persistent voice channel. Perhaps persistent video rooms could also be implemented.

**Describe the solution you'd like**
Maybe a room type such as `m.room.voice` or `m.room.video` would work? I'm not too familiar with the matrix doc so I'm not sure if this is possible with current Matrix technology.
With the upcoming Matrix Spaces (MSC1772), persistent voice rooms and persistent video rooms could add a lot to the experience.

**Comment by turt2live** [comment]
like https://github.com/matrix-org/matrix-spec-proposals/pull/3401
