### ISSUE TITLE
Implement LBRY as a file/media transport.

### ISSUE THREAD

**Issue by irelativism** [matrix-org/matrix-spec#735]
Implement the LBRY protocol as a media and file server/system,
Given it is a very active project and probably the replacement for BitTorrent.
As an addition, maybe such should also be kind of compliant with activityPub as a bonus.

This would fix long standing issues on matrix.org network, and so then one can truly state matrix network is a truly decentralized/distributed system.

**Comment by turt2live** [comment]
I don't foresee us accepting such a proposal, so closing. Happy to be proven wrong with an MSC.
