### ISSUE TITLE
/keys/signatures/upload says that the request format has 'no parameters'

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix-spec#740]
because our doc generator doesn't understand bodies that are just mappings of keys to values.  See if this can be fixed in the new spec site.

**Comment by turt2live** [comment]
new spec site did not fix this

**Comment by uhoreg** [comment]
Same issue with [POST /rooms/{roomId}/receipt/{receiptType}/{eventId}](https://spec.matrix.org/unstable/client-server-api/#post_matrixclientv3roomsroomidreceiptreceipttypeeventid)
