### ISSUE TITLE
OpenAPI: Timestamps should be int64

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/matrix-spec#749]
The following (not conclusively exhaustive) list has timestamps of `integer` type with no specified `format`. When `format` is not specified, [Swagger](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) falls back to [JSON Schema](https://tools.ietf.org/html/draft-zyp-json-schema-04#section-3.5) for type definitions. JSON Schema [conveniently says](https://tools.ietf.org/html/draft-zyp-json-schema-04#section-5.5) that integers should be distinguished from floating-point numbers, and stops at that.

The conclusion from the above is that we should be clear which `integer` is used in each particular place. This issue is about timestamps, which should always be `int64`. The question is - do we need an MSC here or would a _clarification_ be enough.
- [client-server/notifications.yaml](https://github.com/matrix-org/matrix-doc/blob/82a4a028bd523d8ac9b5c46ff4b58cbbe47e998e/api/client-server/notifications.yaml#L126)
- [event-schemas/schema/m.receipt](https://github.com/matrix-org/matrix-doc/blob/82a4a028bd523d8ac9b5c46ff4b58cbbe47e998e/event-schemas/schema/m.receipt#L29) (this one defines `ts` as `number`, not following JSON Schema's spirit; but there's no way to specify precision in JSON Schema so perhaps it's safer to leave it as is).
- [identity/lookup.yaml](https://github.com/matrix-org/matrix-doc/blob/82a4a028bd523d8ac9b5c46ff4b58cbbe47e998e/api/identity/lookup.yaml#L85)
- [identity/associations.yaml](https://github.com/matrix-org/matrix-doc/blob/82a4a028bd523d8ac9b5c46ff4b58cbbe47e998e/api/identity/associations.yaml#L165)
- [identity/v2_associations.yaml](https://github.com/matrix-org/matrix-doc/blob/82a4a028bd523d8ac9b5c46ff4b58cbbe47e998e/api/identity/v2_associations.yaml#L181)
- [push-gateway/push_notifier.yaml](https://github.com/matrix-org/matrix-doc/blob/82a4a028bd523d8ac9b5c46ff4b58cbbe47e998e/api/push-gateway/push_notifier.yaml#L185)

**Comment by turt2live** [comment]
This is another case where the canonical JSON spec disagrees with what we're trying to do with it. https://spec.matrix.org/v1.2/appendices/#signing-json

related: https://github.com/matrix-org/matrix-spec/issues/1085

**Comment by KitsuneRal** [comment]
int64 stores values corresponding to the range specified in the Canonical JSON text, doesn't it?

**Comment by turt2live** [comment]
The spec holds 2^53, not 2^64

**Comment by KitsuneRal** [comment]
I should learn arithmetics, it seems.

That being said, `int64` would still be the best fitting `format` from Swagger perspective, and server-side validations would guard against numbers out of Canonical JSON range.
