### ISSUE TITLE
Spec refers to "token-based login" which seems to no longer exist.

### ISSUE THREAD

**Issue by wbamberg** [matrix-org/matrix-spec#765]
The client-server spec tries to link to "token-based login":

https://github.com/matrix-org/matrix-doc/blob/315cf67f6b713e0bfeb99527767e2d65c4d8e11f/specification/client_server_api.rst#L1074

...but it looks like the target got removed in https://github.com/matrix-org/matrix-doc/pull/2609.

**Comment by turt2live** [comment]
this got fixed
