### ISSUE TITLE
prime characters (') are almost invisible

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-spec#774]
**Link to problem area**:

https://spec.matrix.org/unstable/rooms/v2/#state-resolution

**Issue**

The distinction between `S` and `S'` is absolutely key to this text, and it's almost impossible to distinguish.

![image](https://user-images.githubusercontent.com/1389908/109958528-380ea580-7cde-11eb-8f4d-6a72971467a8.png)

**Comment by DMRobertson** [comment]
(One day, we'll have [MathML everywhere](https://caniuse.com/mathml) and we can trust browsers to lay things out sensibly.)

**Comment by DMRobertson** [comment]
I tried including the prime in the italics. That looks better, but not great in Firefox:

```
sed -e "s/\*S\*′(/*S′*(/g" -i content/rooms/{fragments/v2-state-res.md,v1.md}
```
![Screenshot from 2022-05-03 13-24-25](https://user-images.githubusercontent.com/8614563/166452475-aa7f6883-1ccf-46ba-8893-ca9c4dc7720d.png)
