### ISSUE TITLE
Utilising the currently blank space on the right-hand side

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-spec#775]
We currently leave a lot of unused space on the right-hand side of the screen:

![image](https://user-images.githubusercontent.com/1342360/109961936-82922100-7ce2-11eb-978d-387a7512b058.png)

What are the current plans for this space? My understanding is that we condensed the document text to the middle so that line-lengths wouldn't be too long ([this is known to cause fatigue when reading](https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/Limiting_content_width)). However, some users have reported that they preferred the longer line length.

Docsy uses the right space for a second sidebar that includes helpful links, some of which would equally apply to us:

![image](https://user-images.githubusercontent.com/1342360/109962364-00eec300-7ce3-11eb-8617-b51f9f1824ca.png)

Perhaps a similar sidebar that's optionally collapsible? Equally though those links could be implemented as icons in the top-right of the header and we use this space for something else.

**Comment by richvdh** [comment]
I'm going to close this in favour of #968
