### ISSUE TITLE
Add encryption to the suggested invite_state

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#787]
https://matrix.org/docs/spec/server_server/r0.1.4#put-matrix-federation-v2-invite-roomid-eventid

**Comment by turt2live** [comment]
This happened somewhere, I think. If not, it's a small MSC that doesn't need a tracking issue.

**Comment by clokep** [comment]
[MSC3173](https://github.com/matrix-org/matrix-spec-proposals/pull/3173) specced this.
