### ISSUE TITLE
/sync should be paginated to reduce request size (and generally make it more efficient) 

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#788]
Some sort of pagination (per room or per stream?) would be great for reducing the amount of effort a server has to put in to responding to sync. 

Implementation undefined - needs MSC.

**Comment by KitsuneRal** [comment]
Should this be closed as [sliding sync](https://github.com/matrix-org/matrix-spec-proposals/pull/3575) has shaped up by now? Any further discussion on the subject would most likely run off that new base, anyway.

**Comment by richvdh** [comment]
sounds good to me.
