### ISSUE TITLE
Redesign: Instances of %CLIENT_MAJOR_VERSION% in the text

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-spec#799]
There are instances of the `%CLIENT_MAJOR_VERSION%` placeholder appearing in the spec text, as seen [here](https://spec.matrix.org/unstable/application-service-api/#server-admin-style-permissions). I believe in the old spec this was replaced with the CS API major version number.

I'm not sure how this interacts with the new Matrix Spec Versioning stuff, but we probably want to write a Hugo template for this.

**Comment by KitsuneRal** [comment]
With the transition to individual endpoint versions being done, should this issue be closed?

**Comment by anoadragon453** [comment]
I no longer see this text anywhere in the rendered spec, so I'd say so!

**Comment by aaronraimist** [comment]
@anoadragon453 I still see it on https://spec.matrix.org/unstable/application-service-api/#server-admin-style-permissions
