### ISSUE TITLE
EDU examples have incorrect `edu_type`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-spec#805]
**Link to problem area**:

https://spec.matrix.org/unstable/server-server-api/#receipts, https://spec.matrix.org/unstable/server-server-api/#typing-notifications, etc

**Issue**

The S-S spec contains examples of various EDUs, but they all have `"edu_type": "m.presence"`, despite the fact that most of them are nothing to do with presence.

**Comment by MatMaul** [comment]
The Swagger description seems fine:
https://github.com/matrix-org/matrix-spec/blob/main/data/api/server-server/definitions/event-schemas/m.direct_to_device.yaml#L29

However it seems like the doc generation is taking the `example` from the referenced `edu.yaml` instead:
https://github.com/matrix-org/matrix-spec/blob/main/data/api/server-server/definitions/edu.yaml#L24
