### ISSUE TITLE
Exact Federation `Authorization` header format isn't clear 

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix-spec#817]
#### Link to problem area

https://matrix.org/docs/spec/server_server/r0.1.4#request-authentication

#### Issue
Came up in `#conduit:fachschaften.org`; It's not clear that the parameters after `X-Matrix` can use quotes or not, [RFC2184](https://tools.ietf.org/html/rfc2184) was mentioned with the following quote:

> Note that quotes around parameter values are part of the value
> syntax; they are NOT part of the value itself.  Furthermore, it is
> explicitly permitted to have a mixture of quoted and unquoted
> continuation fields.

Maybe this clarification can be added as an informational footnote.

**Comment by uhoreg** [comment]
The format for the Authorization header is actually in [RFC2735](https://datatracker.ietf.org/doc/html/rfc7235#section-2.1), and *almost* matches what is done in Matrix.  The approach that I've taken in https://github.com/matrix-org/matrix-spec/pull/1067 is to say that we follow RFC2735, but if you want to be nice to servers, follow these more restricted rules.
