### ISSUE TITLE
Remove reference to MAY keyword in local echo section

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#819]
Long ago we decided that MAY is confusing as a keyword: replace it with *might* or similar. Also it's not an all-caps keyword in our spec.

https://spec.matrix.org/unstable/client-server-api/#local-echo

**Comment by richvdh** [comment]
After much discussion on #1550, we don't seem convinced that we want to change this.

(The wording could maybe benefit from clarification but a simple `MAY` -> `might` is not it)
