### ISSUE TITLE
Default invite power-level is incorrect

### ISSUE THREAD

**Issue by clokep** [matrix-org/matrix-spec#860]
https://matrix.org/docs/spec/client_server/latest#m-room-power-levels

**Issue**
The default level for `invite` (if it is not specified) is given as 50.

**Expected behaviour**
According to Synapse it is 0 (see https://github.com/matrix-org/synapse/pull/10254#discussion_r662545610). Note that Synapse defaults *new rooms* to specify an invite level of 50, but when not given it should default to 0. @erikjohnston asserted the spec is incorrect and not Synapse.

See https://github.com/matrix-org/synapse/blob/2d16e69b4bf09b5274a8fa15c8ca4719db8366c1/synapse/event_auth.py#L177 (and other callers of `_get_named_level` with the invite level) which all specify as 0.

It looks like matrix-org/matrix-spec-proposals#341 added these defaults, the others are correct according to Synapse.

**Comment by dkasak** [comment]
Closing this in favour of a new issue I opened with more context. (Sorry, didn't notice this one at first!)

**Comment by dkasak** [comment]
Or rather, I'm not closing it since I don't have the power to do that here. :D But should be fixed by https://github.com/matrix-org/matrix-spec/pull/1021.

**Comment by richvdh** [comment]
I closed the other, since this pre-existed the other and has all the archaeology showing why it is the spec that is wrong.
