### ISSUE TITLE
C2S-OpenAPI should not specify room tag format

### ISSUE THREAD

**Issue by lukaslihotzki** [matrix-org/matrix-spec#875]
C2S-OpenAPI does [specify](https://github.com/matrix-org/matrix-doc/blob/master/data/api/client-server/tags.yaml#L67) the room tag format (currently, only the number `order`).

**Issue**
Synapse doesn't enforce the room tag format. If a client does set an invalid room tag with setRoomTag (order is a string, for example), the server does return this invalid tag to clients, making the homeserver ifself non-conforming.
Dendrite and Conduit reject invalid room tags in setRoomTag, but such data can be set with setAccountDataPerRoom anyway. If getRoomTags is used then, Dendrite and Conduit respond with 500 (Internal Server Error), but is this helpful?

**Expected behaviour**
The C2S-spec should mention that room tags should conform to the [m.tag](https://github.com/matrix-org/matrix-doc/blob/master/data/event-schemas/schema/m.tag.yaml#L20) definition, but not duplicate (and enforce) this definition inside the C2S spec.

**Comment by turt2live** [comment]
We've always taken a stance on account data that the client is ultimately responsible for its own validation of stuff like this, particularly when the server can't reasonably guard a lot of what is stored in account data.

I don't see this as a server being in violation of the spec but rather the client being in violation of the spec, which is almost worse in some respects.

MSCs which attempt to change the stance on validation are welcome.

**Comment by lukaslihotzki** [comment]
It is acceptable that the server does not validate this data, treating is as opaque instead. But then, why is its format specified in the Client-to-Server-API? Server responses of a well-behaving server should always validate against the API definition.

Last time I checked this, some servers (Dendrite or Conduit) validate their responses before sending them. If a client changed the account data directly to an invalid state, such servers returns an Internal Server Error in getRoomTags. Also, clients may validate responses on receive (like FluffyChat based on [matrix_api_lite](https://pub.dev/packages/matrix_api_lite)). This could also lead to the rejection of the whole response.

The spec should define what behavior servers and clients can always rely on and what behavior can only be relied on if no semantically invalid request was ever sent by a client. I think the latter should not be part of the C2S spec at all. Alternatively, such client-supplied, opaque data could be documented by adding a (machine-readable) `"x-client-data": true` key to the spec, so validators can consider these special cases.

**Comment by turt2live** [comment]
there's a lot of discussions which don't fit into issues about how to restructure the client-server api to make it clear what is client data and what is server data, thus describing who and what needs to care about the schema. Account data is no exception to those discussions.
