### ISSUE TITLE
Easy MSC: Migrate `server_name` to `via` to reduce confusion and better match upcoming APIs

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#884]

**Comment by Johennes** [comment]
For the avoidance of doubt, does this issue request to replace the `server_name` query parameter on [`POST /_matrix/client/v3/join/{roomIdOrAlias}`](https://spec.matrix.org/v1.10/client-server-api/#post_matrixclientv3joinroomidoralias) and [`POST /_matrix/client/v3/knock/{roomIdOrAlias}`](https://spec.matrix.org/v1.10/client-server-api/#post_matrixclientv3knockroomidoralias) with a `via` query parameter by way of an MSC?
