### ISSUE TITLE
Percent-encoding examples are inconsistent with text description 

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-spec#900]
**Link to problem area**: https://spec.matrix.org/unstable/appendices/#matrixto-navigation

**Issue**

This area contains the following text:

> The components of the matrix.to URI (`<identifier>` and `<extra parameter>`) are to be percent-encoded as per RFC 3986.
>
> Examples of matrix.to URIs are:
>
> * Room alias: `https://matrix.to/#/%23somewhere%3Aexample.org`
> * Room: `https://matrix.to/#/!somewhere%3Aexample.org`
> * Permalink by room: `https://matrix.to/#/!somewhere%3Aexample.org/%24event%3Aexample.org`
> * Permalink by room alias: `https://matrix.to/#/%23somewhere:example.org/%24event%3Aexample.org`
> * User: `https://matrix.to/#/%40alice%3Aexample.org`

In those examples, `!` is not percent-encoded despite being listed by as a reserved character (to be percent-encoded) by RFC 3986: https://datatracker.ietf.org/doc/html/rfc3986/#page-13

**Expected behaviour**

The `!`s should be percent-encoded, and ideally the characters to be percent-encoded would be listed directly in the spec because digging up the relevant section from the RFC was not easy.

**Comment by turt2live** [comment]
updated link: https://spec.matrix.org/v1.2/appendices/#matrixto-navigation

**Comment by KitsuneRal** [comment]
This is not exactly correct. `!` (same as `$`, that _is_ encoded in the examples though it doesn't need to be) is a sub-delimiter, meaning that it may or may not have a special role in a given URI scheme or even a specific part of a URI scheme. In this particular case, `!` does not have a special delimiter role within the fragment part of `https` scheme - unlike `#`, which does - and therefore doesn't have to (but is allowed to) be percent-encoded.

That said, `matrix.to` accepts `#` unencoded too, for the sake of usability (although strictly speaking it does fall out of RFC compliance in this regard). This is addressed in an INFO box below the examples, as of Matrix 1.2 (among some other considerations, which boil down to admitting unencoded delimiters whenever it's unambiguous but encoding general delimiters - `#` and `/`, namely - when emitting `matrix.to` URIs.

**Comment by turt2live** [comment]
not sure what we'd improve? Maybe a link to the actual section, but beyond that it's really not something the Matrix spec should be specifying. 

for reference: https://datatracker.ietf.org/doc/html/rfc3986#section-2.1
