### ISSUE TITLE
`PusherData` is undocumented in the Push Gateway API

### ISSUE THREAD

**Issue by dkasak** [matrix-org/matrix-spec#910]
**Link to problem area**:

https://spec.matrix.org/unstable/push-gateway-api/

**Issue**

`PusherData` is mentioned in https://spec.matrix.org/unstable/push-gateway-api/, but the format is not spelled out anywhere. `event_id_only` and `format` are mentioned, but do not link to anywhere. It *is* spelled out in the [C2S API](https://spec.matrix.org/unstable/client-server-api/#post_matrixclientv3pushersset), though, if that's supposed to be the same thing.

The Push Gateway API should either spell out what `PusherData` is or link to an appropriate section elsewhere.

**Comment by richvdh** [comment]
> `PushData` is mentioned in [spec.matrix.org/unstable/push-gateway-api](https://spec.matrix.org/unstable/push-gateway-api/), but the format is not spelled out anywhere.

I guess this meant to say `PusherData`.

**Comment by dkasak** [comment]
Ugh, yes. The title says as much but I typoed in the body. I'll edit.
