### ISSUE TITLE
PusherData documentation doesn't mention default_payload field

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-spec#921]
**Link to problem area**: Seems like this type is defined twice and should be de-duplicated. Both in the same file, first occurrence [here](https://github.com/matrix-org/matrix-doc/blob/95d850c418ee544a25ee33c19c8fd65deedbf868/data/api/client-server/pusher.yaml#L107-L124).

**Issue**

The `PusherData` definition doesn't mention the `default_payload` field which is apparently has to be set for notification to work *at all* on iOS: https://github.com/matrix-org/sygnal/blob/main/docs/applications.md#ios-applications-beware

**Comment by Johennes** [comment]
`default_payload` is a sygnal-specific field that was added in https://github.com/matrix-org/sygnal/pull/127. [MSC2631](https://github.com/matrix-org/matrix-spec-proposals/pull/2631) attempted to spec it but @richvdh (I believe correctly) determined that this shouldn't go into the spec. The gateway is provided by the client developer and the concrete push notification payload, including any default fields, is an implementation detail between the client and its gateway. Therefore, I believe this should be closed.

**Comment by richvdh** [comment]
Indeed, I don't think this should be in the spec.

**Comment by jplatte** [comment]
Then I think we should have a note that the `PusherData` can contain arbitrary extra fields _that are important to be passed through_ though.

**Comment by jplatte** [comment]
Not sure what you mean.. I'm talking from the perspective of the homeserver: The context of this issue, AFAIK, is that there used to be a bug in Conduit where it deserialized the `PusherData` (as part of a larger request body) into a Ruma type and re-serialized it for the push gateway, losing this field - see https://github.com/ruma/ruma/issues/753 (should be listed above because it has a back-reference to here).

**Comment by Johennes** [comment]
I think additional properties being allowed is the [default](https://github.com/matrix-org/matrix-spec/blob/ae3673d2ef72156085d3e1f7dbd923e15dd2ae29/layouts/partials/openapi/render-object-table.html#L62-L63) for pretty much all objects in Matrix already?

**Comment by jplatte** [comment]
Yes, _allowing_ them is required pretty much everywhere. That's not the same though. When objects like this need to be passed through in their original form elsewhere, I think it would be useful for that to be highlighted.

Lots of things are sent to a server and only interpreted there (event contents being a notable exception), so it doesn't matter whether they're parsed into some general "JSON object" form, unknown fields being deserialized but never read; or parsed into a type that only contains the known fields. In the latter case, serializing the parsed request or parts of it again loses any unknown fields, which is what that bug was about.

**Comment by Johennes** [comment]
Oh, you mean a note pointing out that `data` should be passed through unmodified except for removing the `url` field? I think the gateway API already tries to explain that:

https://github.com/matrix-org/matrix-spec/blob/ae3673d2ef72156085d3e1f7dbd923e15dd2ae29/data/api/push-gateway/push_notifier.yaml#L181-L187

It could help to also mention that in the CS API though. 👍
