### ISSUE TITLE
Consider splitting MSCs and spec into separate github repositories

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-spec#927]
Combining MSCs and finalised spec docs into a single repo brings several problems:

 * Pull requests have a *very* different lifecycle. It is hard to keep on top of non-MSC PRs, which generally get merged much quicker than MSC PRs. (It is possible to use labels to do some filtering, but I still think it means that spec PRs tend to get forgotten)
 * Having 291 open PRs is, rightly or wrongly, seen as a terrible smell for a project of this size. At least we could compartmentalise it into a single "proposals" repository.
 * I generally think it's a bit confusing for new contributors.
 * As a spec author, it's often necessary to have two checkouts for matrix-doc: one for MSCs and one for spec writing: the tooling conflicts with MSC branches.

I think my strategy to fix it would be:

 *  close as many non-MSC matrix-doc PRs as possible (https://github.com/matrix-org/matrix-doc/pulls?q=is%3Aopen+is%3Apr+-label%3Aproposal)
 * create a new copy of the repo at `matrix-org/matrix-spec`
 * rename `matrix-doc` to `matrix-spec-proposals` (thus retaining HTTP links to existing MSCs)
 * remove the irrelevant bits from each repo
 * recreate any remaining non-MSC matrix-doc PRs against `matrix-spec`
 * transfer all of the issues to `matrix-spec`. Process for this involves https://github.com/github/hub:
   ```
   # get a list of issues
   hub issue -f '%I%n' > issues.txt
   # transfer them all
   while read issue; do
       hub issue transfer $issue `matrix-org/matrix-spec`
   done < issues.txt
   ```

**Comment by anoadragon453** [comment]
- [ ] Update the text on https://spec.matrix.org/unstable/proposals/ to point to the new repositories.

**Comment by richvdh** [comment]
I think this is done, to a good approximation
