### ISSUE TITLE
m.call.answer sample has an invalid field.

### ISSUE THREAD

**Issue by Dominaezzz** [matrix-org/matrix-spec#931]
**Link to problem area**:
See the `lifetime` field here,
https://github.com/matrix-org/matrix-doc/blob/8d9a67d9f64c51be3e8465d7db1f1de5f47faa7a/data/event-schemas/examples/m.call.answer.yaml#L4-L12
it's not actually in the schema.
https://github.com/matrix-org/matrix-doc/blob/8d9a67d9f64c51be3e8465d7db1f1de5f47faa7a/data/event-schemas/schema/m.call.answer.yaml#L8-L38

**Issue**

Correct the sample or the schema.

**Comment by KitsuneRal** [comment]
Ftr, after checking across a couple of Element implementations: `lifetime` seems to be an accidental entry in the example and should not be a part of the specced event content. It's also pretty hard to devise why it would be needed in an answer event even in theory.
