### ISSUE TITLE
Restricted rooms in space hierarchy are missing allow conditions

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-spec#984]
**Link to problem area**: https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv1roomsroomidhierarchy

**Issue**

The `PublicRoomsChunk` documentation in the response section to the `GET …/hierarchy` endpoint has this to say about the `join_rule` field:

> The room’s join rule. When not present, the room is assumed to be `public`.

However, it does not mention any fields that define the rules by which one is allowed to join the room. Is the idea there that seeing the room in the response at all means that the user who issued the request is allowed to join?

In practice, Synapse sends a `allowed_room_ids` which covers the only currently-specced type of allow condition, but represented in a different way than the same condition is represented in the room's `m.room.join_rules` (array of room IDs vs. array of objects).

**Comment by clokep** [comment]
If the room is available in the response it should be joinable (or the user is already joined), yes.

Synapse should not be returning that died to clients, if it is that's a bug! That field should only be used for server-server API.

**Comment by jplatte** [comment]
Okay, I'll create a Synapse bug report then 😅

**Comment by jplatte** [comment]
Closing in favor of the Synapse issue.
