### ISSUE TITLE
Build fails with hugo 0.92.0+

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-spec#986]
> Error: Error building site: "/home/jplatte/code/matrix-spec/content/client-server-api/_[index.md:2293](http://index.md:2293/):1": failed to render shortcode "cs-module": failed to process shortcode: "/home/jplatte/code/matrix-spec/layouts/shortcodes/cs-module.html:12:42": execute of template failed: template: shortcodes/cs-module.html:12:42: executing "shortcodes/cs-module.html" at <.Page.Dir>: can't evaluate field Dir in type [page.Page](http://page.page/)[](https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$ykRSehREShnNAHpuVfx0NRi9oaW9gQmOMhFB5VE8uWA?via=matrix.org&via=libera.chat&via=element.io)

**Comment by anoadragon453** [comment]
`Page.Dir` also fails in [hugo v0.92.0](https://github.com/gohugoio/hugo/releases/tag/v0.92.0), as that release caused the function to raise an error.
