### ISSUE TITLE
[Spec idea]: ActivityPub integration

### ISSUE THREAD

**Issue by tristan-cottam** [matrix-org/matrix-spec#995]
Matrix could integrate with [ActivityPub](https://activitypub.rocks/) to allow users to connect with all other users of the ActivityPub Fediverse. This would allow Matrix to comply with W3C standards, and increase in visibility and usability.

**Comment by MTRNord** [comment]
This probably better fits into a bridge than the proto itself as they differ greatly.

**Comment by Henri2h** [comment]
Take a look at https://gitlab.com/kazarma/kazarma

**Comment by turt2live** [comment]
This is indeed better served as a bridge at this stage.
